// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module my_NN_NN_func (
        ap_clk,
        ap_rst,
        U0,
        U1,
        U2,
        x0_i,
        x0_o,
        x0_o_ap_vld,
        x1_i,
        x1_o,
        x1_o_ap_vld,
        x2_i,
        x2_o,
        x2_o_ap_vld,
        x3_i,
        x3_o,
        x3_o_ap_vld,
        my_NN_tanh_0_V,
        my_NN_tanh_1_V,
        my_NN_tanh_2_V,
        my_NN_tanh_3_V,
        my_NN_tanh_4_V,
        my_NN_tanh_5_V,
        my_NN_tanh_6_V,
        my_NN_tanh_7_V,
        my_NN_tanh_8_V,
        my_NN_tanh_9_V,
        my_NN_tanh_10_V,
        my_NN_tanh_11_V,
        my_NN_tanh_12_V,
        my_NN_tanh_13_V,
        my_NN_tanh_14_V,
        my_NN_tanh_15_V,
        my_NN_tanh_16_V,
        my_NN_tanh_17_V,
        my_NN_tanh_18_V,
        my_NN_tanh_19_V,
        my_NN_tanh_20_V,
        my_NN_tanh_21_V,
        my_NN_tanh_22_V,
        my_NN_tanh_23_V,
        my_NN_tanh_24_V,
        my_NN_tanh_25_V,
        my_NN_tanh_26_V,
        my_NN_tanh_27_V,
        my_NN_tanh_28_V,
        my_NN_tanh_29_V,
        my_NN_tanh_30_V,
        my_NN_tanh_31_V,
        my_NN_tanh_32_V,
        my_NN_tanh_33_V,
        my_NN_tanh_34_V,
        my_NN_tanh_35_V,
        my_NN_tanh_36_V,
        my_NN_tanh_37_V,
        my_NN_tanh_38_V,
        my_NN_tanh_39_V,
        my_NN_tanh_40_V,
        my_NN_tanh_41_V,
        my_NN_tanh_42_V,
        my_NN_tanh_43_V,
        my_NN_tanh_44_V,
        my_NN_tanh_45_V,
        my_NN_tanh_46_V,
        my_NN_tanh_47_V,
        my_NN_tanh_48_V,
        my_NN_tanh_49_V,
        my_NN_tanh_50_V,
        my_NN_tanh_51_V,
        my_NN_tanh_52_V,
        my_NN_tanh_53_V,
        my_NN_tanh_54_V,
        my_NN_tanh_55_V,
        my_NN_tanh_56_V,
        my_NN_tanh_57_V,
        my_NN_tanh_58_V,
        my_NN_tanh_59_V,
        my_NN_tanh_60_V,
        my_NN_tanh_61_V,
        my_NN_tanh_62_V,
        my_NN_tanh_63_V,
        my_NN_tanh_64_V,
        my_NN_tanh_65_V,
        my_NN_tanh_66_V,
        my_NN_tanh_67_V,
        my_NN_tanh_68_V,
        my_NN_tanh_69_V,
        my_NN_tanh_70_V,
        my_NN_tanh_71_V,
        my_NN_tanh_72_V,
        my_NN_tanh_73_V,
        my_NN_tanh_74_V,
        my_NN_tanh_75_V,
        my_NN_tanh_76_V,
        my_NN_tanh_77_V,
        my_NN_tanh_78_V,
        my_NN_tanh_79_V,
        my_NN_tanh_80_V,
        my_NN_tanh_81_V,
        my_NN_tanh_82_V,
        my_NN_tanh_83_V,
        my_NN_tanh_84_V,
        my_NN_tanh_85_V,
        my_NN_tanh_86_V,
        my_NN_tanh_87_V,
        my_NN_tanh_88_V,
        my_NN_tanh_89_V,
        my_NN_tanh_90_V,
        my_NN_tanh_91_V,
        my_NN_tanh_92_V,
        my_NN_tanh_93_V,
        my_NN_tanh_94_V,
        my_NN_tanh_95_V,
        my_NN_tanh_96_V,
        my_NN_tanh_97_V,
        my_NN_tanh_98_V,
        my_NN_tanh_99_V,
        my_NN_tanh_100_V,
        my_NN_tanh_101_V,
        my_NN_tanh_102_V,
        my_NN_tanh_103_V,
        my_NN_tanh_104_V,
        my_NN_tanh_105_V,
        my_NN_tanh_106_V,
        my_NN_tanh_107_V,
        my_NN_tanh_108_V,
        my_NN_tanh_109_V,
        my_NN_tanh_110_V,
        my_NN_tanh_111_V,
        my_NN_tanh_112_V,
        my_NN_tanh_113_V,
        my_NN_tanh_114_V,
        my_NN_tanh_115_V,
        my_NN_tanh_116_V,
        my_NN_tanh_117_V,
        my_NN_tanh_118_V,
        my_NN_tanh_119_V,
        my_NN_tanh_120_V,
        my_NN_tanh_121_V,
        my_NN_tanh_122_V,
        my_NN_tanh_123_V,
        my_NN_tanh_124_V,
        my_NN_tanh_125_V,
        my_NN_tanh_126_V,
        my_NN_tanh_127_V,
        my_NN_b_0_V,
        my_NN_b_1_V,
        my_NN_b_2_V,
        my_NN_b_3_V,
        my_NN_b_4_V,
        my_NN_b_5_V,
        my_NN_b_6_V,
        my_NN_b_7_V,
        my_NN_b_8_V,
        my_NN_b_9_V,
        my_NN_b_10_V,
        my_NN_b_11_V,
        my_NN_w_0_V,
        my_NN_w_1_V,
        my_NN_w_2_V,
        my_NN_w_3_V,
        my_NN_w_4_V,
        my_NN_w_5_V,
        my_NN_w_6_V,
        my_NN_w_7_V,
        my_NN_w_8_V,
        my_NN_w_9_V,
        my_NN_w_10_V,
        my_NN_w_11_V,
        my_NN_w_12_V,
        my_NN_w_13_V,
        my_NN_w_14_V,
        my_NN_w_15_V,
        my_NN_w_16_V,
        my_NN_w_17_V,
        my_NN_w_18_V,
        my_NN_w_19_V,
        my_NN_w_20_V,
        my_NN_w_21_V,
        my_NN_w_22_V,
        my_NN_w_23_V,
        my_NN_w_24_V,
        my_NN_w_25_V,
        my_NN_w_26_V,
        my_NN_w_27_V,
        my_NN_w_28_V,
        my_NN_w_29_V,
        my_NN_w_30_V,
        my_NN_w_31_V,
        my_NN_w_32_V,
        my_NN_w_33_V,
        my_NN_w_34_V,
        my_NN_w_35_V,
        my_NN_w_36_V,
        my_NN_w_37_V,
        my_NN_w_38_V,
        my_NN_w_39_V,
        my_NN_w_40_V,
        my_NN_w_41_V,
        my_NN_w_42_V,
        my_NN_w_43_V,
        my_NN_w_44_V,
        my_NN_w_45_V,
        my_NN_w_46_V,
        my_NN_w_47_V,
        my_NN_w_48_V,
        my_NN_w_49_V,
        my_NN_w_50_V,
        my_NN_w_51_V,
        my_NN_w_52_V,
        my_NN_w_53_V,
        my_NN_w_54_V,
        my_NN_w_55_V,
        my_NN_w_56_V,
        my_NN_w_57_V,
        my_NN_w_58_V,
        my_NN_w_59_V,
        my_NN_w_60_V,
        my_NN_w_61_V,
        my_NN_w_62_V,
        my_NN_w_63_V,
        my_NN_n_V_i,
        my_NN_n_V_o,
        my_NN_n_V_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;


input   ap_clk;
input   ap_rst;
input  [17:0] U0;
input  [17:0] U1;
input  [17:0] U2;
input  [17:0] x0_i;
output  [17:0] x0_o;
output   x0_o_ap_vld;
input  [17:0] x1_i;
output  [17:0] x1_o;
output   x1_o_ap_vld;
input  [17:0] x2_i;
output  [17:0] x2_o;
output   x2_o_ap_vld;
input  [17:0] x3_i;
output  [17:0] x3_o;
output   x3_o_ap_vld;
input  [17:0] my_NN_tanh_0_V;
input  [17:0] my_NN_tanh_1_V;
input  [17:0] my_NN_tanh_2_V;
input  [17:0] my_NN_tanh_3_V;
input  [17:0] my_NN_tanh_4_V;
input  [17:0] my_NN_tanh_5_V;
input  [17:0] my_NN_tanh_6_V;
input  [17:0] my_NN_tanh_7_V;
input  [17:0] my_NN_tanh_8_V;
input  [17:0] my_NN_tanh_9_V;
input  [17:0] my_NN_tanh_10_V;
input  [17:0] my_NN_tanh_11_V;
input  [17:0] my_NN_tanh_12_V;
input  [17:0] my_NN_tanh_13_V;
input  [17:0] my_NN_tanh_14_V;
input  [17:0] my_NN_tanh_15_V;
input  [17:0] my_NN_tanh_16_V;
input  [17:0] my_NN_tanh_17_V;
input  [17:0] my_NN_tanh_18_V;
input  [17:0] my_NN_tanh_19_V;
input  [17:0] my_NN_tanh_20_V;
input  [17:0] my_NN_tanh_21_V;
input  [17:0] my_NN_tanh_22_V;
input  [17:0] my_NN_tanh_23_V;
input  [17:0] my_NN_tanh_24_V;
input  [17:0] my_NN_tanh_25_V;
input  [17:0] my_NN_tanh_26_V;
input  [17:0] my_NN_tanh_27_V;
input  [17:0] my_NN_tanh_28_V;
input  [17:0] my_NN_tanh_29_V;
input  [17:0] my_NN_tanh_30_V;
input  [17:0] my_NN_tanh_31_V;
input  [17:0] my_NN_tanh_32_V;
input  [17:0] my_NN_tanh_33_V;
input  [17:0] my_NN_tanh_34_V;
input  [17:0] my_NN_tanh_35_V;
input  [17:0] my_NN_tanh_36_V;
input  [17:0] my_NN_tanh_37_V;
input  [17:0] my_NN_tanh_38_V;
input  [17:0] my_NN_tanh_39_V;
input  [17:0] my_NN_tanh_40_V;
input  [17:0] my_NN_tanh_41_V;
input  [17:0] my_NN_tanh_42_V;
input  [17:0] my_NN_tanh_43_V;
input  [17:0] my_NN_tanh_44_V;
input  [17:0] my_NN_tanh_45_V;
input  [17:0] my_NN_tanh_46_V;
input  [17:0] my_NN_tanh_47_V;
input  [17:0] my_NN_tanh_48_V;
input  [17:0] my_NN_tanh_49_V;
input  [17:0] my_NN_tanh_50_V;
input  [17:0] my_NN_tanh_51_V;
input  [17:0] my_NN_tanh_52_V;
input  [17:0] my_NN_tanh_53_V;
input  [17:0] my_NN_tanh_54_V;
input  [17:0] my_NN_tanh_55_V;
input  [17:0] my_NN_tanh_56_V;
input  [17:0] my_NN_tanh_57_V;
input  [17:0] my_NN_tanh_58_V;
input  [17:0] my_NN_tanh_59_V;
input  [17:0] my_NN_tanh_60_V;
input  [17:0] my_NN_tanh_61_V;
input  [17:0] my_NN_tanh_62_V;
input  [17:0] my_NN_tanh_63_V;
input  [17:0] my_NN_tanh_64_V;
input  [17:0] my_NN_tanh_65_V;
input  [17:0] my_NN_tanh_66_V;
input  [17:0] my_NN_tanh_67_V;
input  [17:0] my_NN_tanh_68_V;
input  [17:0] my_NN_tanh_69_V;
input  [17:0] my_NN_tanh_70_V;
input  [17:0] my_NN_tanh_71_V;
input  [17:0] my_NN_tanh_72_V;
input  [17:0] my_NN_tanh_73_V;
input  [17:0] my_NN_tanh_74_V;
input  [17:0] my_NN_tanh_75_V;
input  [17:0] my_NN_tanh_76_V;
input  [17:0] my_NN_tanh_77_V;
input  [17:0] my_NN_tanh_78_V;
input  [17:0] my_NN_tanh_79_V;
input  [17:0] my_NN_tanh_80_V;
input  [17:0] my_NN_tanh_81_V;
input  [17:0] my_NN_tanh_82_V;
input  [17:0] my_NN_tanh_83_V;
input  [17:0] my_NN_tanh_84_V;
input  [17:0] my_NN_tanh_85_V;
input  [17:0] my_NN_tanh_86_V;
input  [17:0] my_NN_tanh_87_V;
input  [17:0] my_NN_tanh_88_V;
input  [17:0] my_NN_tanh_89_V;
input  [17:0] my_NN_tanh_90_V;
input  [17:0] my_NN_tanh_91_V;
input  [17:0] my_NN_tanh_92_V;
input  [17:0] my_NN_tanh_93_V;
input  [17:0] my_NN_tanh_94_V;
input  [17:0] my_NN_tanh_95_V;
input  [17:0] my_NN_tanh_96_V;
input  [17:0] my_NN_tanh_97_V;
input  [17:0] my_NN_tanh_98_V;
input  [17:0] my_NN_tanh_99_V;
input  [17:0] my_NN_tanh_100_V;
input  [17:0] my_NN_tanh_101_V;
input  [17:0] my_NN_tanh_102_V;
input  [17:0] my_NN_tanh_103_V;
input  [17:0] my_NN_tanh_104_V;
input  [17:0] my_NN_tanh_105_V;
input  [17:0] my_NN_tanh_106_V;
input  [17:0] my_NN_tanh_107_V;
input  [17:0] my_NN_tanh_108_V;
input  [17:0] my_NN_tanh_109_V;
input  [17:0] my_NN_tanh_110_V;
input  [17:0] my_NN_tanh_111_V;
input  [17:0] my_NN_tanh_112_V;
input  [17:0] my_NN_tanh_113_V;
input  [17:0] my_NN_tanh_114_V;
input  [17:0] my_NN_tanh_115_V;
input  [17:0] my_NN_tanh_116_V;
input  [17:0] my_NN_tanh_117_V;
input  [17:0] my_NN_tanh_118_V;
input  [17:0] my_NN_tanh_119_V;
input  [17:0] my_NN_tanh_120_V;
input  [17:0] my_NN_tanh_121_V;
input  [17:0] my_NN_tanh_122_V;
input  [17:0] my_NN_tanh_123_V;
input  [17:0] my_NN_tanh_124_V;
input  [17:0] my_NN_tanh_125_V;
input  [17:0] my_NN_tanh_126_V;
input  [17:0] my_NN_tanh_127_V;
input  [17:0] my_NN_b_0_V;
input  [17:0] my_NN_b_1_V;
input  [17:0] my_NN_b_2_V;
input  [17:0] my_NN_b_3_V;
input  [17:0] my_NN_b_4_V;
input  [17:0] my_NN_b_5_V;
input  [17:0] my_NN_b_6_V;
input  [17:0] my_NN_b_7_V;
input  [17:0] my_NN_b_8_V;
input  [17:0] my_NN_b_9_V;
input  [17:0] my_NN_b_10_V;
input  [17:0] my_NN_b_11_V;
input  [17:0] my_NN_w_0_V;
input  [17:0] my_NN_w_1_V;
input  [17:0] my_NN_w_2_V;
input  [17:0] my_NN_w_3_V;
input  [17:0] my_NN_w_4_V;
input  [17:0] my_NN_w_5_V;
input  [17:0] my_NN_w_6_V;
input  [17:0] my_NN_w_7_V;
input  [17:0] my_NN_w_8_V;
input  [17:0] my_NN_w_9_V;
input  [17:0] my_NN_w_10_V;
input  [17:0] my_NN_w_11_V;
input  [17:0] my_NN_w_12_V;
input  [17:0] my_NN_w_13_V;
input  [17:0] my_NN_w_14_V;
input  [17:0] my_NN_w_15_V;
input  [17:0] my_NN_w_16_V;
input  [17:0] my_NN_w_17_V;
input  [17:0] my_NN_w_18_V;
input  [17:0] my_NN_w_19_V;
input  [17:0] my_NN_w_20_V;
input  [17:0] my_NN_w_21_V;
input  [17:0] my_NN_w_22_V;
input  [17:0] my_NN_w_23_V;
input  [17:0] my_NN_w_24_V;
input  [17:0] my_NN_w_25_V;
input  [17:0] my_NN_w_26_V;
input  [17:0] my_NN_w_27_V;
input  [17:0] my_NN_w_28_V;
input  [17:0] my_NN_w_29_V;
input  [17:0] my_NN_w_30_V;
input  [17:0] my_NN_w_31_V;
input  [17:0] my_NN_w_32_V;
input  [17:0] my_NN_w_33_V;
input  [17:0] my_NN_w_34_V;
input  [17:0] my_NN_w_35_V;
input  [17:0] my_NN_w_36_V;
input  [17:0] my_NN_w_37_V;
input  [17:0] my_NN_w_38_V;
input  [17:0] my_NN_w_39_V;
input  [17:0] my_NN_w_40_V;
input  [17:0] my_NN_w_41_V;
input  [17:0] my_NN_w_42_V;
input  [17:0] my_NN_w_43_V;
input  [17:0] my_NN_w_44_V;
input  [17:0] my_NN_w_45_V;
input  [17:0] my_NN_w_46_V;
input  [17:0] my_NN_w_47_V;
input  [17:0] my_NN_w_48_V;
input  [17:0] my_NN_w_49_V;
input  [17:0] my_NN_w_50_V;
input  [17:0] my_NN_w_51_V;
input  [17:0] my_NN_w_52_V;
input  [17:0] my_NN_w_53_V;
input  [17:0] my_NN_w_54_V;
input  [17:0] my_NN_w_55_V;
input  [17:0] my_NN_w_56_V;
input  [17:0] my_NN_w_57_V;
input  [17:0] my_NN_w_58_V;
input  [17:0] my_NN_w_59_V;
input  [17:0] my_NN_w_60_V;
input  [17:0] my_NN_w_61_V;
input  [17:0] my_NN_w_62_V;
input  [17:0] my_NN_w_63_V;
input  [2:0] my_NN_n_V_i;
output  [2:0] my_NN_n_V_o;
output   my_NN_n_V_o_ap_vld;

reg[17:0] x0_o;
reg x0_o_ap_vld;
reg[17:0] x1_o;
reg x1_o_ap_vld;
reg[17:0] x2_o;
reg x2_o_ap_vld;
reg[17:0] x3_o;
reg x3_o_ap_vld;
reg my_NN_n_V_o_ap_vld;

wire   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_16_fu_2417_p2;
wire   [1:0] tmp_73_fu_1829_p1;
wire   [0:0] sel_tmp5_fu_1845_p2;
wire   [0:0] sel_tmp3_fu_1839_p2;
wire   [0:0] sel_tmp_fu_1833_p2;
wire   [0:0] or_cond_fu_1859_p2;
wire   [17:0] newSel_fu_1851_p3;
wire   [17:0] newSel1_fu_1865_p3;
wire  signed [17:0] newSel2_fu_1873_p3;
wire  signed [17:0] OP2_V_fu_1885_p0;
wire   [17:0] newSel3_fu_1889_p3;
wire   [17:0] newSel4_fu_1897_p3;
wire  signed [17:0] newSel5_fu_1905_p3;
wire  signed [17:0] OP2_V_1_fu_1917_p0;
wire  signed [35:0] p_Val2_s_fu_3764_p2;
wire   [17:0] newSel6_fu_1924_p3;
wire   [17:0] newSel7_fu_1932_p3;
wire  signed [17:0] newSel8_fu_1940_p3;
wire  signed [17:0] OP2_V_2_fu_1952_p0;
wire  signed [36:0] grp_fu_3771_p3;
wire  signed [35:0] p_Val2_12_fu_3780_p2;
wire   [37:0] tmp_2_fu_1956_p1;
wire   [37:0] tmp_3_fu_1959_p1;
wire   [17:0] newSel9_fu_1968_p3;
wire   [17:0] newSel10_fu_1976_p3;
wire  signed [17:0] newSel11_fu_1984_p3;
wire  signed [17:0] OP2_V_3_fu_1996_p0;
wire  signed [35:0] p_Val2_13_fu_3787_p2;
wire   [37:0] p_Val2_16_fu_1962_p2;
wire   [37:0] tmp_17_cast_fu_2000_p1;
wire   [17:0] newSel12_fu_2009_p3;
wire   [17:0] newSel13_fu_2017_p3;
wire  signed [17:0] newSel14_fu_2025_p3;
wire   [17:0] newSel15_fu_2037_p3;
wire   [17:0] newSel16_fu_2045_p3;
wire  signed [17:0] newSel17_fu_2053_p3;
wire  signed [35:0] p_Val2_19_fu_3794_p2;
wire   [17:0] newSel18_fu_2068_p3;
wire   [17:0] newSel19_fu_2076_p3;
wire  signed [17:0] newSel20_fu_2084_p3;
wire  signed [36:0] grp_fu_3801_p3;
wire  signed [35:0] p_Val2_20_fu_3810_p2;
wire   [37:0] tmp_6_fu_2096_p1;
wire   [37:0] tmp_7_fu_2099_p1;
wire   [17:0] newSel21_fu_2108_p3;
wire   [17:0] newSel22_fu_2116_p3;
wire  signed [17:0] newSel23_fu_2124_p3;
wire  signed [35:0] p_Val2_22_fu_3817_p2;
wire   [37:0] p_Val2_23_fu_2102_p2;
wire   [37:0] tmp_23_cast_fu_2136_p1;
wire   [17:0] newSel24_fu_2145_p3;
wire   [17:0] newSel25_fu_2153_p3;
wire  signed [17:0] newSel26_fu_2161_p3;
wire   [17:0] newSel27_fu_2173_p3;
wire   [17:0] newSel28_fu_2181_p3;
wire  signed [17:0] newSel29_fu_2189_p3;
wire  signed [35:0] p_Val2_26_fu_3824_p2;
wire   [17:0] newSel30_fu_2204_p3;
wire   [17:0] newSel31_fu_2212_p3;
wire  signed [17:0] newSel32_fu_2220_p3;
wire  signed [36:0] grp_fu_3831_p3;
wire  signed [35:0] p_Val2_27_fu_3840_p2;
wire   [37:0] tmp_10_fu_2232_p1;
wire   [37:0] tmp_11_fu_2235_p1;
wire   [17:0] newSel33_fu_2244_p3;
wire   [17:0] newSel34_fu_2252_p3;
wire  signed [17:0] newSel35_fu_2260_p3;
wire  signed [35:0] p_Val2_29_fu_3847_p2;
wire   [37:0] p_Val2_30_fu_2238_p2;
wire   [37:0] tmp_29_cast_fu_2272_p1;
wire   [17:0] newSel36_fu_2281_p3;
wire   [17:0] newSel37_fu_2289_p3;
wire  signed [17:0] newSel38_fu_2297_p3;
wire   [17:0] newSel39_fu_2309_p3;
wire   [17:0] newSel40_fu_2317_p3;
wire  signed [17:0] newSel41_fu_2325_p3;
wire  signed [35:0] p_Val2_33_fu_3854_p2;
wire   [17:0] newSel42_fu_2340_p3;
wire   [17:0] newSel43_fu_2348_p3;
wire  signed [17:0] newSel44_fu_2356_p3;
wire  signed [36:0] grp_fu_3861_p3;
wire  signed [35:0] p_Val2_34_fu_3870_p2;
wire   [37:0] tmp_14_fu_2368_p1;
wire   [37:0] tmp_15_fu_2371_p1;
wire   [17:0] newSel45_fu_2380_p3;
wire   [17:0] newSel46_fu_2388_p3;
wire  signed [17:0] newSel47_fu_2396_p3;
wire  signed [35:0] p_Val2_36_fu_3877_p2;
wire   [37:0] p_Val2_37_fu_2374_p2;
wire   [37:0] tmp_35_cast_fu_2408_p1;
wire   [37:0] p_Val2_17_fu_2003_p2;
wire  signed [17:0] tmp_41_fu_2437_p0;
wire   [6:0] p_Val2_46_fu_2441_p129;
wire   [17:0] p_Val2_46_fu_2441_p130;
wire  signed [17:0] tmp_45_fu_2715_p0;
wire  signed [17:0] tmp_49_fu_2723_p0;
wire  signed [29:0] grp_fu_3900_p3;
wire   [37:0] p_Val2_24_fu_2139_p2;
wire   [6:0] p_Val2_49_fu_2751_p129;
wire   [17:0] p_Val2_49_fu_2751_p130;
wire  signed [29:0] grp_fu_3925_p3;
wire   [37:0] p_Val2_31_fu_2275_p2;
wire   [6:0] p_Val2_52_fu_3053_p129;
wire   [17:0] p_Val2_52_fu_3053_p130;
wire  signed [29:0] grp_fu_3950_p3;
wire   [37:0] p_Val2_38_fu_2411_p2;
wire   [6:0] p_Val2_55_fu_3355_p129;
wire   [17:0] p_Val2_55_fu_3355_p130;
wire  signed [29:0] grp_fu_3975_p3;
wire  signed [17:0] tmp_17_fu_3643_p0;
wire  signed [17:0] tmp_19_fu_3651_p0;
wire  signed [17:0] tmp_23_fu_3659_p0;
wire  signed [29:0] grp_fu_3998_p3;
wire  signed [29:0] grp_fu_4021_p3;
wire  signed [29:0] grp_fu_4044_p3;
wire  signed [29:0] grp_fu_4067_p3;
wire   [0:0] tmp_71_fu_3743_p2;
wire   [2:0] tmp_72_fu_3749_p2;
wire  signed [17:0] p_Val2_s_fu_3764_p1;
wire  signed [35:0] OP2_V_fu_1885_p1;
wire  signed [17:0] grp_fu_3771_p1;
wire  signed [35:0] OP2_V_1_fu_1917_p1;
wire  signed [17:0] p_Val2_12_fu_3780_p1;
wire  signed [35:0] OP2_V_2_fu_1952_p1;
wire  signed [17:0] p_Val2_13_fu_3787_p1;
wire  signed [35:0] OP2_V_3_fu_1996_p1;
wire  signed [17:0] p_Val2_19_fu_3794_p0;
wire  signed [17:0] grp_fu_3801_p0;
wire  signed [17:0] p_Val2_20_fu_3810_p0;
wire  signed [17:0] p_Val2_22_fu_3817_p0;
wire  signed [17:0] p_Val2_26_fu_3824_p0;
wire  signed [17:0] grp_fu_3831_p0;
wire  signed [17:0] p_Val2_27_fu_3840_p0;
wire  signed [17:0] p_Val2_29_fu_3847_p0;
wire  signed [17:0] p_Val2_33_fu_3854_p0;
wire  signed [17:0] grp_fu_3861_p0;
wire  signed [17:0] p_Val2_34_fu_3870_p0;
wire  signed [17:0] p_Val2_36_fu_3877_p1;
wire  signed [17:0] grp_fu_3884_p1;
wire  signed [29:0] tmp_41_fu_2437_p1;
wire   [29:0] grp_fu_3884_p2;
wire  signed [17:0] grp_fu_3892_p1;
wire  signed [29:0] tmp_45_fu_2715_p1;
wire  signed [29:0] grp_fu_3884_p3;
wire  signed [17:0] grp_fu_3900_p1;
wire  signed [29:0] tmp_49_fu_2723_p1;
wire  signed [29:0] grp_fu_3892_p3;
wire  signed [17:0] grp_fu_3909_p1;
wire   [29:0] grp_fu_3909_p2;
wire  signed [17:0] grp_fu_3917_p1;
wire  signed [29:0] grp_fu_3909_p3;
wire  signed [17:0] grp_fu_3925_p1;
wire  signed [29:0] grp_fu_3917_p3;
wire  signed [17:0] grp_fu_3934_p1;
wire   [29:0] grp_fu_3934_p2;
wire  signed [17:0] grp_fu_3942_p1;
wire  signed [29:0] grp_fu_3934_p3;
wire  signed [17:0] grp_fu_3950_p1;
wire  signed [29:0] grp_fu_3942_p3;
wire  signed [17:0] grp_fu_3959_p1;
wire   [29:0] grp_fu_3959_p2;
wire  signed [17:0] grp_fu_3967_p1;
wire  signed [29:0] grp_fu_3959_p3;
wire  signed [17:0] grp_fu_3975_p1;
wire  signed [29:0] grp_fu_3967_p3;
wire  signed [17:0] grp_fu_3984_p0;
wire  signed [29:0] tmp_17_fu_3643_p1;
wire  signed [29:0] tmp_22_fu_3991_p2;
wire  signed [17:0] tmp_22_fu_3991_p0;
wire  signed [29:0] tmp_19_fu_3651_p1;
wire  signed [17:0] grp_fu_3998_p0;
wire  signed [29:0] tmp_23_fu_3659_p1;
wire  signed [29:0] grp_fu_3984_p3;
wire  signed [17:0] grp_fu_4007_p0;
wire  signed [29:0] tmp_28_fu_4014_p2;
wire  signed [17:0] tmp_28_fu_4014_p0;
wire  signed [17:0] grp_fu_4021_p0;
wire  signed [29:0] grp_fu_4007_p3;
wire  signed [17:0] grp_fu_4030_p0;
wire  signed [29:0] tmp_33_fu_4037_p2;
wire  signed [17:0] tmp_33_fu_4037_p0;
wire  signed [17:0] grp_fu_4044_p0;
wire  signed [29:0] grp_fu_4030_p3;
wire  signed [17:0] grp_fu_4053_p0;
wire  signed [29:0] tmp_38_fu_4060_p2;
wire  signed [17:0] tmp_38_fu_4060_p0;
wire  signed [17:0] grp_fu_4067_p0;
wire  signed [29:0] grp_fu_4053_p3;
reg   [0:0] ap_NS_fsm;

my_NN_mux_1287_18bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 18 ),
    .din11_WIDTH( 18 ),
    .din12_WIDTH( 18 ),
    .din13_WIDTH( 18 ),
    .din14_WIDTH( 18 ),
    .din15_WIDTH( 18 ),
    .din16_WIDTH( 18 ),
    .din17_WIDTH( 18 ),
    .din18_WIDTH( 18 ),
    .din19_WIDTH( 18 ),
    .din20_WIDTH( 18 ),
    .din21_WIDTH( 18 ),
    .din22_WIDTH( 18 ),
    .din23_WIDTH( 18 ),
    .din24_WIDTH( 18 ),
    .din25_WIDTH( 18 ),
    .din26_WIDTH( 18 ),
    .din27_WIDTH( 18 ),
    .din28_WIDTH( 18 ),
    .din29_WIDTH( 18 ),
    .din30_WIDTH( 18 ),
    .din31_WIDTH( 18 ),
    .din32_WIDTH( 18 ),
    .din33_WIDTH( 18 ),
    .din34_WIDTH( 18 ),
    .din35_WIDTH( 18 ),
    .din36_WIDTH( 18 ),
    .din37_WIDTH( 18 ),
    .din38_WIDTH( 18 ),
    .din39_WIDTH( 18 ),
    .din40_WIDTH( 18 ),
    .din41_WIDTH( 18 ),
    .din42_WIDTH( 18 ),
    .din43_WIDTH( 18 ),
    .din44_WIDTH( 18 ),
    .din45_WIDTH( 18 ),
    .din46_WIDTH( 18 ),
    .din47_WIDTH( 18 ),
    .din48_WIDTH( 18 ),
    .din49_WIDTH( 18 ),
    .din50_WIDTH( 18 ),
    .din51_WIDTH( 18 ),
    .din52_WIDTH( 18 ),
    .din53_WIDTH( 18 ),
    .din54_WIDTH( 18 ),
    .din55_WIDTH( 18 ),
    .din56_WIDTH( 18 ),
    .din57_WIDTH( 18 ),
    .din58_WIDTH( 18 ),
    .din59_WIDTH( 18 ),
    .din60_WIDTH( 18 ),
    .din61_WIDTH( 18 ),
    .din62_WIDTH( 18 ),
    .din63_WIDTH( 18 ),
    .din64_WIDTH( 18 ),
    .din65_WIDTH( 18 ),
    .din66_WIDTH( 18 ),
    .din67_WIDTH( 18 ),
    .din68_WIDTH( 18 ),
    .din69_WIDTH( 18 ),
    .din70_WIDTH( 18 ),
    .din71_WIDTH( 18 ),
    .din72_WIDTH( 18 ),
    .din73_WIDTH( 18 ),
    .din74_WIDTH( 18 ),
    .din75_WIDTH( 18 ),
    .din76_WIDTH( 18 ),
    .din77_WIDTH( 18 ),
    .din78_WIDTH( 18 ),
    .din79_WIDTH( 18 ),
    .din80_WIDTH( 18 ),
    .din81_WIDTH( 18 ),
    .din82_WIDTH( 18 ),
    .din83_WIDTH( 18 ),
    .din84_WIDTH( 18 ),
    .din85_WIDTH( 18 ),
    .din86_WIDTH( 18 ),
    .din87_WIDTH( 18 ),
    .din88_WIDTH( 18 ),
    .din89_WIDTH( 18 ),
    .din90_WIDTH( 18 ),
    .din91_WIDTH( 18 ),
    .din92_WIDTH( 18 ),
    .din93_WIDTH( 18 ),
    .din94_WIDTH( 18 ),
    .din95_WIDTH( 18 ),
    .din96_WIDTH( 18 ),
    .din97_WIDTH( 18 ),
    .din98_WIDTH( 18 ),
    .din99_WIDTH( 18 ),
    .din100_WIDTH( 18 ),
    .din101_WIDTH( 18 ),
    .din102_WIDTH( 18 ),
    .din103_WIDTH( 18 ),
    .din104_WIDTH( 18 ),
    .din105_WIDTH( 18 ),
    .din106_WIDTH( 18 ),
    .din107_WIDTH( 18 ),
    .din108_WIDTH( 18 ),
    .din109_WIDTH( 18 ),
    .din110_WIDTH( 18 ),
    .din111_WIDTH( 18 ),
    .din112_WIDTH( 18 ),
    .din113_WIDTH( 18 ),
    .din114_WIDTH( 18 ),
    .din115_WIDTH( 18 ),
    .din116_WIDTH( 18 ),
    .din117_WIDTH( 18 ),
    .din118_WIDTH( 18 ),
    .din119_WIDTH( 18 ),
    .din120_WIDTH( 18 ),
    .din121_WIDTH( 18 ),
    .din122_WIDTH( 18 ),
    .din123_WIDTH( 18 ),
    .din124_WIDTH( 18 ),
    .din125_WIDTH( 18 ),
    .din126_WIDTH( 18 ),
    .din127_WIDTH( 18 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
my_NN_mux_1287_18bkb_U1(
    .din0(my_NN_tanh_0_V),
    .din1(my_NN_tanh_1_V),
    .din2(my_NN_tanh_2_V),
    .din3(my_NN_tanh_3_V),
    .din4(my_NN_tanh_4_V),
    .din5(my_NN_tanh_5_V),
    .din6(my_NN_tanh_6_V),
    .din7(my_NN_tanh_7_V),
    .din8(my_NN_tanh_8_V),
    .din9(my_NN_tanh_9_V),
    .din10(my_NN_tanh_10_V),
    .din11(my_NN_tanh_11_V),
    .din12(my_NN_tanh_12_V),
    .din13(my_NN_tanh_13_V),
    .din14(my_NN_tanh_14_V),
    .din15(my_NN_tanh_15_V),
    .din16(my_NN_tanh_16_V),
    .din17(my_NN_tanh_17_V),
    .din18(my_NN_tanh_18_V),
    .din19(my_NN_tanh_19_V),
    .din20(my_NN_tanh_20_V),
    .din21(my_NN_tanh_21_V),
    .din22(my_NN_tanh_22_V),
    .din23(my_NN_tanh_23_V),
    .din24(my_NN_tanh_24_V),
    .din25(my_NN_tanh_25_V),
    .din26(my_NN_tanh_26_V),
    .din27(my_NN_tanh_27_V),
    .din28(my_NN_tanh_28_V),
    .din29(my_NN_tanh_29_V),
    .din30(my_NN_tanh_30_V),
    .din31(my_NN_tanh_31_V),
    .din32(my_NN_tanh_32_V),
    .din33(my_NN_tanh_33_V),
    .din34(my_NN_tanh_34_V),
    .din35(my_NN_tanh_35_V),
    .din36(my_NN_tanh_36_V),
    .din37(my_NN_tanh_37_V),
    .din38(my_NN_tanh_38_V),
    .din39(my_NN_tanh_39_V),
    .din40(my_NN_tanh_40_V),
    .din41(my_NN_tanh_41_V),
    .din42(my_NN_tanh_42_V),
    .din43(my_NN_tanh_43_V),
    .din44(my_NN_tanh_44_V),
    .din45(my_NN_tanh_45_V),
    .din46(my_NN_tanh_46_V),
    .din47(my_NN_tanh_47_V),
    .din48(my_NN_tanh_48_V),
    .din49(my_NN_tanh_49_V),
    .din50(my_NN_tanh_50_V),
    .din51(my_NN_tanh_51_V),
    .din52(my_NN_tanh_52_V),
    .din53(my_NN_tanh_53_V),
    .din54(my_NN_tanh_54_V),
    .din55(my_NN_tanh_55_V),
    .din56(my_NN_tanh_56_V),
    .din57(my_NN_tanh_57_V),
    .din58(my_NN_tanh_58_V),
    .din59(my_NN_tanh_59_V),
    .din60(my_NN_tanh_60_V),
    .din61(my_NN_tanh_61_V),
    .din62(my_NN_tanh_62_V),
    .din63(my_NN_tanh_63_V),
    .din64(my_NN_tanh_64_V),
    .din65(my_NN_tanh_65_V),
    .din66(my_NN_tanh_66_V),
    .din67(my_NN_tanh_67_V),
    .din68(my_NN_tanh_68_V),
    .din69(my_NN_tanh_69_V),
    .din70(my_NN_tanh_70_V),
    .din71(my_NN_tanh_71_V),
    .din72(my_NN_tanh_72_V),
    .din73(my_NN_tanh_73_V),
    .din74(my_NN_tanh_74_V),
    .din75(my_NN_tanh_75_V),
    .din76(my_NN_tanh_76_V),
    .din77(my_NN_tanh_77_V),
    .din78(my_NN_tanh_78_V),
    .din79(my_NN_tanh_79_V),
    .din80(my_NN_tanh_80_V),
    .din81(my_NN_tanh_81_V),
    .din82(my_NN_tanh_82_V),
    .din83(my_NN_tanh_83_V),
    .din84(my_NN_tanh_84_V),
    .din85(my_NN_tanh_85_V),
    .din86(my_NN_tanh_86_V),
    .din87(my_NN_tanh_87_V),
    .din88(my_NN_tanh_88_V),
    .din89(my_NN_tanh_89_V),
    .din90(my_NN_tanh_90_V),
    .din91(my_NN_tanh_91_V),
    .din92(my_NN_tanh_92_V),
    .din93(my_NN_tanh_93_V),
    .din94(my_NN_tanh_94_V),
    .din95(my_NN_tanh_95_V),
    .din96(my_NN_tanh_96_V),
    .din97(my_NN_tanh_97_V),
    .din98(my_NN_tanh_98_V),
    .din99(my_NN_tanh_99_V),
    .din100(my_NN_tanh_100_V),
    .din101(my_NN_tanh_101_V),
    .din102(my_NN_tanh_102_V),
    .din103(my_NN_tanh_103_V),
    .din104(my_NN_tanh_104_V),
    .din105(my_NN_tanh_105_V),
    .din106(my_NN_tanh_106_V),
    .din107(my_NN_tanh_107_V),
    .din108(my_NN_tanh_108_V),
    .din109(my_NN_tanh_109_V),
    .din110(my_NN_tanh_110_V),
    .din111(my_NN_tanh_111_V),
    .din112(my_NN_tanh_112_V),
    .din113(my_NN_tanh_113_V),
    .din114(my_NN_tanh_114_V),
    .din115(my_NN_tanh_115_V),
    .din116(my_NN_tanh_116_V),
    .din117(my_NN_tanh_117_V),
    .din118(my_NN_tanh_118_V),
    .din119(my_NN_tanh_119_V),
    .din120(my_NN_tanh_120_V),
    .din121(my_NN_tanh_121_V),
    .din122(my_NN_tanh_122_V),
    .din123(my_NN_tanh_123_V),
    .din124(my_NN_tanh_124_V),
    .din125(my_NN_tanh_125_V),
    .din126(my_NN_tanh_126_V),
    .din127(my_NN_tanh_127_V),
    .din128(p_Val2_46_fu_2441_p129),
    .dout(p_Val2_46_fu_2441_p130)
);

my_NN_mux_1287_18bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 18 ),
    .din11_WIDTH( 18 ),
    .din12_WIDTH( 18 ),
    .din13_WIDTH( 18 ),
    .din14_WIDTH( 18 ),
    .din15_WIDTH( 18 ),
    .din16_WIDTH( 18 ),
    .din17_WIDTH( 18 ),
    .din18_WIDTH( 18 ),
    .din19_WIDTH( 18 ),
    .din20_WIDTH( 18 ),
    .din21_WIDTH( 18 ),
    .din22_WIDTH( 18 ),
    .din23_WIDTH( 18 ),
    .din24_WIDTH( 18 ),
    .din25_WIDTH( 18 ),
    .din26_WIDTH( 18 ),
    .din27_WIDTH( 18 ),
    .din28_WIDTH( 18 ),
    .din29_WIDTH( 18 ),
    .din30_WIDTH( 18 ),
    .din31_WIDTH( 18 ),
    .din32_WIDTH( 18 ),
    .din33_WIDTH( 18 ),
    .din34_WIDTH( 18 ),
    .din35_WIDTH( 18 ),
    .din36_WIDTH( 18 ),
    .din37_WIDTH( 18 ),
    .din38_WIDTH( 18 ),
    .din39_WIDTH( 18 ),
    .din40_WIDTH( 18 ),
    .din41_WIDTH( 18 ),
    .din42_WIDTH( 18 ),
    .din43_WIDTH( 18 ),
    .din44_WIDTH( 18 ),
    .din45_WIDTH( 18 ),
    .din46_WIDTH( 18 ),
    .din47_WIDTH( 18 ),
    .din48_WIDTH( 18 ),
    .din49_WIDTH( 18 ),
    .din50_WIDTH( 18 ),
    .din51_WIDTH( 18 ),
    .din52_WIDTH( 18 ),
    .din53_WIDTH( 18 ),
    .din54_WIDTH( 18 ),
    .din55_WIDTH( 18 ),
    .din56_WIDTH( 18 ),
    .din57_WIDTH( 18 ),
    .din58_WIDTH( 18 ),
    .din59_WIDTH( 18 ),
    .din60_WIDTH( 18 ),
    .din61_WIDTH( 18 ),
    .din62_WIDTH( 18 ),
    .din63_WIDTH( 18 ),
    .din64_WIDTH( 18 ),
    .din65_WIDTH( 18 ),
    .din66_WIDTH( 18 ),
    .din67_WIDTH( 18 ),
    .din68_WIDTH( 18 ),
    .din69_WIDTH( 18 ),
    .din70_WIDTH( 18 ),
    .din71_WIDTH( 18 ),
    .din72_WIDTH( 18 ),
    .din73_WIDTH( 18 ),
    .din74_WIDTH( 18 ),
    .din75_WIDTH( 18 ),
    .din76_WIDTH( 18 ),
    .din77_WIDTH( 18 ),
    .din78_WIDTH( 18 ),
    .din79_WIDTH( 18 ),
    .din80_WIDTH( 18 ),
    .din81_WIDTH( 18 ),
    .din82_WIDTH( 18 ),
    .din83_WIDTH( 18 ),
    .din84_WIDTH( 18 ),
    .din85_WIDTH( 18 ),
    .din86_WIDTH( 18 ),
    .din87_WIDTH( 18 ),
    .din88_WIDTH( 18 ),
    .din89_WIDTH( 18 ),
    .din90_WIDTH( 18 ),
    .din91_WIDTH( 18 ),
    .din92_WIDTH( 18 ),
    .din93_WIDTH( 18 ),
    .din94_WIDTH( 18 ),
    .din95_WIDTH( 18 ),
    .din96_WIDTH( 18 ),
    .din97_WIDTH( 18 ),
    .din98_WIDTH( 18 ),
    .din99_WIDTH( 18 ),
    .din100_WIDTH( 18 ),
    .din101_WIDTH( 18 ),
    .din102_WIDTH( 18 ),
    .din103_WIDTH( 18 ),
    .din104_WIDTH( 18 ),
    .din105_WIDTH( 18 ),
    .din106_WIDTH( 18 ),
    .din107_WIDTH( 18 ),
    .din108_WIDTH( 18 ),
    .din109_WIDTH( 18 ),
    .din110_WIDTH( 18 ),
    .din111_WIDTH( 18 ),
    .din112_WIDTH( 18 ),
    .din113_WIDTH( 18 ),
    .din114_WIDTH( 18 ),
    .din115_WIDTH( 18 ),
    .din116_WIDTH( 18 ),
    .din117_WIDTH( 18 ),
    .din118_WIDTH( 18 ),
    .din119_WIDTH( 18 ),
    .din120_WIDTH( 18 ),
    .din121_WIDTH( 18 ),
    .din122_WIDTH( 18 ),
    .din123_WIDTH( 18 ),
    .din124_WIDTH( 18 ),
    .din125_WIDTH( 18 ),
    .din126_WIDTH( 18 ),
    .din127_WIDTH( 18 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
my_NN_mux_1287_18bkb_U2(
    .din0(my_NN_tanh_0_V),
    .din1(my_NN_tanh_1_V),
    .din2(my_NN_tanh_2_V),
    .din3(my_NN_tanh_3_V),
    .din4(my_NN_tanh_4_V),
    .din5(my_NN_tanh_5_V),
    .din6(my_NN_tanh_6_V),
    .din7(my_NN_tanh_7_V),
    .din8(my_NN_tanh_8_V),
    .din9(my_NN_tanh_9_V),
    .din10(my_NN_tanh_10_V),
    .din11(my_NN_tanh_11_V),
    .din12(my_NN_tanh_12_V),
    .din13(my_NN_tanh_13_V),
    .din14(my_NN_tanh_14_V),
    .din15(my_NN_tanh_15_V),
    .din16(my_NN_tanh_16_V),
    .din17(my_NN_tanh_17_V),
    .din18(my_NN_tanh_18_V),
    .din19(my_NN_tanh_19_V),
    .din20(my_NN_tanh_20_V),
    .din21(my_NN_tanh_21_V),
    .din22(my_NN_tanh_22_V),
    .din23(my_NN_tanh_23_V),
    .din24(my_NN_tanh_24_V),
    .din25(my_NN_tanh_25_V),
    .din26(my_NN_tanh_26_V),
    .din27(my_NN_tanh_27_V),
    .din28(my_NN_tanh_28_V),
    .din29(my_NN_tanh_29_V),
    .din30(my_NN_tanh_30_V),
    .din31(my_NN_tanh_31_V),
    .din32(my_NN_tanh_32_V),
    .din33(my_NN_tanh_33_V),
    .din34(my_NN_tanh_34_V),
    .din35(my_NN_tanh_35_V),
    .din36(my_NN_tanh_36_V),
    .din37(my_NN_tanh_37_V),
    .din38(my_NN_tanh_38_V),
    .din39(my_NN_tanh_39_V),
    .din40(my_NN_tanh_40_V),
    .din41(my_NN_tanh_41_V),
    .din42(my_NN_tanh_42_V),
    .din43(my_NN_tanh_43_V),
    .din44(my_NN_tanh_44_V),
    .din45(my_NN_tanh_45_V),
    .din46(my_NN_tanh_46_V),
    .din47(my_NN_tanh_47_V),
    .din48(my_NN_tanh_48_V),
    .din49(my_NN_tanh_49_V),
    .din50(my_NN_tanh_50_V),
    .din51(my_NN_tanh_51_V),
    .din52(my_NN_tanh_52_V),
    .din53(my_NN_tanh_53_V),
    .din54(my_NN_tanh_54_V),
    .din55(my_NN_tanh_55_V),
    .din56(my_NN_tanh_56_V),
    .din57(my_NN_tanh_57_V),
    .din58(my_NN_tanh_58_V),
    .din59(my_NN_tanh_59_V),
    .din60(my_NN_tanh_60_V),
    .din61(my_NN_tanh_61_V),
    .din62(my_NN_tanh_62_V),
    .din63(my_NN_tanh_63_V),
    .din64(my_NN_tanh_64_V),
    .din65(my_NN_tanh_65_V),
    .din66(my_NN_tanh_66_V),
    .din67(my_NN_tanh_67_V),
    .din68(my_NN_tanh_68_V),
    .din69(my_NN_tanh_69_V),
    .din70(my_NN_tanh_70_V),
    .din71(my_NN_tanh_71_V),
    .din72(my_NN_tanh_72_V),
    .din73(my_NN_tanh_73_V),
    .din74(my_NN_tanh_74_V),
    .din75(my_NN_tanh_75_V),
    .din76(my_NN_tanh_76_V),
    .din77(my_NN_tanh_77_V),
    .din78(my_NN_tanh_78_V),
    .din79(my_NN_tanh_79_V),
    .din80(my_NN_tanh_80_V),
    .din81(my_NN_tanh_81_V),
    .din82(my_NN_tanh_82_V),
    .din83(my_NN_tanh_83_V),
    .din84(my_NN_tanh_84_V),
    .din85(my_NN_tanh_85_V),
    .din86(my_NN_tanh_86_V),
    .din87(my_NN_tanh_87_V),
    .din88(my_NN_tanh_88_V),
    .din89(my_NN_tanh_89_V),
    .din90(my_NN_tanh_90_V),
    .din91(my_NN_tanh_91_V),
    .din92(my_NN_tanh_92_V),
    .din93(my_NN_tanh_93_V),
    .din94(my_NN_tanh_94_V),
    .din95(my_NN_tanh_95_V),
    .din96(my_NN_tanh_96_V),
    .din97(my_NN_tanh_97_V),
    .din98(my_NN_tanh_98_V),
    .din99(my_NN_tanh_99_V),
    .din100(my_NN_tanh_100_V),
    .din101(my_NN_tanh_101_V),
    .din102(my_NN_tanh_102_V),
    .din103(my_NN_tanh_103_V),
    .din104(my_NN_tanh_104_V),
    .din105(my_NN_tanh_105_V),
    .din106(my_NN_tanh_106_V),
    .din107(my_NN_tanh_107_V),
    .din108(my_NN_tanh_108_V),
    .din109(my_NN_tanh_109_V),
    .din110(my_NN_tanh_110_V),
    .din111(my_NN_tanh_111_V),
    .din112(my_NN_tanh_112_V),
    .din113(my_NN_tanh_113_V),
    .din114(my_NN_tanh_114_V),
    .din115(my_NN_tanh_115_V),
    .din116(my_NN_tanh_116_V),
    .din117(my_NN_tanh_117_V),
    .din118(my_NN_tanh_118_V),
    .din119(my_NN_tanh_119_V),
    .din120(my_NN_tanh_120_V),
    .din121(my_NN_tanh_121_V),
    .din122(my_NN_tanh_122_V),
    .din123(my_NN_tanh_123_V),
    .din124(my_NN_tanh_124_V),
    .din125(my_NN_tanh_125_V),
    .din126(my_NN_tanh_126_V),
    .din127(my_NN_tanh_127_V),
    .din128(p_Val2_49_fu_2751_p129),
    .dout(p_Val2_49_fu_2751_p130)
);

my_NN_mux_1287_18bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 18 ),
    .din11_WIDTH( 18 ),
    .din12_WIDTH( 18 ),
    .din13_WIDTH( 18 ),
    .din14_WIDTH( 18 ),
    .din15_WIDTH( 18 ),
    .din16_WIDTH( 18 ),
    .din17_WIDTH( 18 ),
    .din18_WIDTH( 18 ),
    .din19_WIDTH( 18 ),
    .din20_WIDTH( 18 ),
    .din21_WIDTH( 18 ),
    .din22_WIDTH( 18 ),
    .din23_WIDTH( 18 ),
    .din24_WIDTH( 18 ),
    .din25_WIDTH( 18 ),
    .din26_WIDTH( 18 ),
    .din27_WIDTH( 18 ),
    .din28_WIDTH( 18 ),
    .din29_WIDTH( 18 ),
    .din30_WIDTH( 18 ),
    .din31_WIDTH( 18 ),
    .din32_WIDTH( 18 ),
    .din33_WIDTH( 18 ),
    .din34_WIDTH( 18 ),
    .din35_WIDTH( 18 ),
    .din36_WIDTH( 18 ),
    .din37_WIDTH( 18 ),
    .din38_WIDTH( 18 ),
    .din39_WIDTH( 18 ),
    .din40_WIDTH( 18 ),
    .din41_WIDTH( 18 ),
    .din42_WIDTH( 18 ),
    .din43_WIDTH( 18 ),
    .din44_WIDTH( 18 ),
    .din45_WIDTH( 18 ),
    .din46_WIDTH( 18 ),
    .din47_WIDTH( 18 ),
    .din48_WIDTH( 18 ),
    .din49_WIDTH( 18 ),
    .din50_WIDTH( 18 ),
    .din51_WIDTH( 18 ),
    .din52_WIDTH( 18 ),
    .din53_WIDTH( 18 ),
    .din54_WIDTH( 18 ),
    .din55_WIDTH( 18 ),
    .din56_WIDTH( 18 ),
    .din57_WIDTH( 18 ),
    .din58_WIDTH( 18 ),
    .din59_WIDTH( 18 ),
    .din60_WIDTH( 18 ),
    .din61_WIDTH( 18 ),
    .din62_WIDTH( 18 ),
    .din63_WIDTH( 18 ),
    .din64_WIDTH( 18 ),
    .din65_WIDTH( 18 ),
    .din66_WIDTH( 18 ),
    .din67_WIDTH( 18 ),
    .din68_WIDTH( 18 ),
    .din69_WIDTH( 18 ),
    .din70_WIDTH( 18 ),
    .din71_WIDTH( 18 ),
    .din72_WIDTH( 18 ),
    .din73_WIDTH( 18 ),
    .din74_WIDTH( 18 ),
    .din75_WIDTH( 18 ),
    .din76_WIDTH( 18 ),
    .din77_WIDTH( 18 ),
    .din78_WIDTH( 18 ),
    .din79_WIDTH( 18 ),
    .din80_WIDTH( 18 ),
    .din81_WIDTH( 18 ),
    .din82_WIDTH( 18 ),
    .din83_WIDTH( 18 ),
    .din84_WIDTH( 18 ),
    .din85_WIDTH( 18 ),
    .din86_WIDTH( 18 ),
    .din87_WIDTH( 18 ),
    .din88_WIDTH( 18 ),
    .din89_WIDTH( 18 ),
    .din90_WIDTH( 18 ),
    .din91_WIDTH( 18 ),
    .din92_WIDTH( 18 ),
    .din93_WIDTH( 18 ),
    .din94_WIDTH( 18 ),
    .din95_WIDTH( 18 ),
    .din96_WIDTH( 18 ),
    .din97_WIDTH( 18 ),
    .din98_WIDTH( 18 ),
    .din99_WIDTH( 18 ),
    .din100_WIDTH( 18 ),
    .din101_WIDTH( 18 ),
    .din102_WIDTH( 18 ),
    .din103_WIDTH( 18 ),
    .din104_WIDTH( 18 ),
    .din105_WIDTH( 18 ),
    .din106_WIDTH( 18 ),
    .din107_WIDTH( 18 ),
    .din108_WIDTH( 18 ),
    .din109_WIDTH( 18 ),
    .din110_WIDTH( 18 ),
    .din111_WIDTH( 18 ),
    .din112_WIDTH( 18 ),
    .din113_WIDTH( 18 ),
    .din114_WIDTH( 18 ),
    .din115_WIDTH( 18 ),
    .din116_WIDTH( 18 ),
    .din117_WIDTH( 18 ),
    .din118_WIDTH( 18 ),
    .din119_WIDTH( 18 ),
    .din120_WIDTH( 18 ),
    .din121_WIDTH( 18 ),
    .din122_WIDTH( 18 ),
    .din123_WIDTH( 18 ),
    .din124_WIDTH( 18 ),
    .din125_WIDTH( 18 ),
    .din126_WIDTH( 18 ),
    .din127_WIDTH( 18 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
my_NN_mux_1287_18bkb_U3(
    .din0(my_NN_tanh_0_V),
    .din1(my_NN_tanh_1_V),
    .din2(my_NN_tanh_2_V),
    .din3(my_NN_tanh_3_V),
    .din4(my_NN_tanh_4_V),
    .din5(my_NN_tanh_5_V),
    .din6(my_NN_tanh_6_V),
    .din7(my_NN_tanh_7_V),
    .din8(my_NN_tanh_8_V),
    .din9(my_NN_tanh_9_V),
    .din10(my_NN_tanh_10_V),
    .din11(my_NN_tanh_11_V),
    .din12(my_NN_tanh_12_V),
    .din13(my_NN_tanh_13_V),
    .din14(my_NN_tanh_14_V),
    .din15(my_NN_tanh_15_V),
    .din16(my_NN_tanh_16_V),
    .din17(my_NN_tanh_17_V),
    .din18(my_NN_tanh_18_V),
    .din19(my_NN_tanh_19_V),
    .din20(my_NN_tanh_20_V),
    .din21(my_NN_tanh_21_V),
    .din22(my_NN_tanh_22_V),
    .din23(my_NN_tanh_23_V),
    .din24(my_NN_tanh_24_V),
    .din25(my_NN_tanh_25_V),
    .din26(my_NN_tanh_26_V),
    .din27(my_NN_tanh_27_V),
    .din28(my_NN_tanh_28_V),
    .din29(my_NN_tanh_29_V),
    .din30(my_NN_tanh_30_V),
    .din31(my_NN_tanh_31_V),
    .din32(my_NN_tanh_32_V),
    .din33(my_NN_tanh_33_V),
    .din34(my_NN_tanh_34_V),
    .din35(my_NN_tanh_35_V),
    .din36(my_NN_tanh_36_V),
    .din37(my_NN_tanh_37_V),
    .din38(my_NN_tanh_38_V),
    .din39(my_NN_tanh_39_V),
    .din40(my_NN_tanh_40_V),
    .din41(my_NN_tanh_41_V),
    .din42(my_NN_tanh_42_V),
    .din43(my_NN_tanh_43_V),
    .din44(my_NN_tanh_44_V),
    .din45(my_NN_tanh_45_V),
    .din46(my_NN_tanh_46_V),
    .din47(my_NN_tanh_47_V),
    .din48(my_NN_tanh_48_V),
    .din49(my_NN_tanh_49_V),
    .din50(my_NN_tanh_50_V),
    .din51(my_NN_tanh_51_V),
    .din52(my_NN_tanh_52_V),
    .din53(my_NN_tanh_53_V),
    .din54(my_NN_tanh_54_V),
    .din55(my_NN_tanh_55_V),
    .din56(my_NN_tanh_56_V),
    .din57(my_NN_tanh_57_V),
    .din58(my_NN_tanh_58_V),
    .din59(my_NN_tanh_59_V),
    .din60(my_NN_tanh_60_V),
    .din61(my_NN_tanh_61_V),
    .din62(my_NN_tanh_62_V),
    .din63(my_NN_tanh_63_V),
    .din64(my_NN_tanh_64_V),
    .din65(my_NN_tanh_65_V),
    .din66(my_NN_tanh_66_V),
    .din67(my_NN_tanh_67_V),
    .din68(my_NN_tanh_68_V),
    .din69(my_NN_tanh_69_V),
    .din70(my_NN_tanh_70_V),
    .din71(my_NN_tanh_71_V),
    .din72(my_NN_tanh_72_V),
    .din73(my_NN_tanh_73_V),
    .din74(my_NN_tanh_74_V),
    .din75(my_NN_tanh_75_V),
    .din76(my_NN_tanh_76_V),
    .din77(my_NN_tanh_77_V),
    .din78(my_NN_tanh_78_V),
    .din79(my_NN_tanh_79_V),
    .din80(my_NN_tanh_80_V),
    .din81(my_NN_tanh_81_V),
    .din82(my_NN_tanh_82_V),
    .din83(my_NN_tanh_83_V),
    .din84(my_NN_tanh_84_V),
    .din85(my_NN_tanh_85_V),
    .din86(my_NN_tanh_86_V),
    .din87(my_NN_tanh_87_V),
    .din88(my_NN_tanh_88_V),
    .din89(my_NN_tanh_89_V),
    .din90(my_NN_tanh_90_V),
    .din91(my_NN_tanh_91_V),
    .din92(my_NN_tanh_92_V),
    .din93(my_NN_tanh_93_V),
    .din94(my_NN_tanh_94_V),
    .din95(my_NN_tanh_95_V),
    .din96(my_NN_tanh_96_V),
    .din97(my_NN_tanh_97_V),
    .din98(my_NN_tanh_98_V),
    .din99(my_NN_tanh_99_V),
    .din100(my_NN_tanh_100_V),
    .din101(my_NN_tanh_101_V),
    .din102(my_NN_tanh_102_V),
    .din103(my_NN_tanh_103_V),
    .din104(my_NN_tanh_104_V),
    .din105(my_NN_tanh_105_V),
    .din106(my_NN_tanh_106_V),
    .din107(my_NN_tanh_107_V),
    .din108(my_NN_tanh_108_V),
    .din109(my_NN_tanh_109_V),
    .din110(my_NN_tanh_110_V),
    .din111(my_NN_tanh_111_V),
    .din112(my_NN_tanh_112_V),
    .din113(my_NN_tanh_113_V),
    .din114(my_NN_tanh_114_V),
    .din115(my_NN_tanh_115_V),
    .din116(my_NN_tanh_116_V),
    .din117(my_NN_tanh_117_V),
    .din118(my_NN_tanh_118_V),
    .din119(my_NN_tanh_119_V),
    .din120(my_NN_tanh_120_V),
    .din121(my_NN_tanh_121_V),
    .din122(my_NN_tanh_122_V),
    .din123(my_NN_tanh_123_V),
    .din124(my_NN_tanh_124_V),
    .din125(my_NN_tanh_125_V),
    .din126(my_NN_tanh_126_V),
    .din127(my_NN_tanh_127_V),
    .din128(p_Val2_52_fu_3053_p129),
    .dout(p_Val2_52_fu_3053_p130)
);

my_NN_mux_1287_18bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 18 ),
    .din11_WIDTH( 18 ),
    .din12_WIDTH( 18 ),
    .din13_WIDTH( 18 ),
    .din14_WIDTH( 18 ),
    .din15_WIDTH( 18 ),
    .din16_WIDTH( 18 ),
    .din17_WIDTH( 18 ),
    .din18_WIDTH( 18 ),
    .din19_WIDTH( 18 ),
    .din20_WIDTH( 18 ),
    .din21_WIDTH( 18 ),
    .din22_WIDTH( 18 ),
    .din23_WIDTH( 18 ),
    .din24_WIDTH( 18 ),
    .din25_WIDTH( 18 ),
    .din26_WIDTH( 18 ),
    .din27_WIDTH( 18 ),
    .din28_WIDTH( 18 ),
    .din29_WIDTH( 18 ),
    .din30_WIDTH( 18 ),
    .din31_WIDTH( 18 ),
    .din32_WIDTH( 18 ),
    .din33_WIDTH( 18 ),
    .din34_WIDTH( 18 ),
    .din35_WIDTH( 18 ),
    .din36_WIDTH( 18 ),
    .din37_WIDTH( 18 ),
    .din38_WIDTH( 18 ),
    .din39_WIDTH( 18 ),
    .din40_WIDTH( 18 ),
    .din41_WIDTH( 18 ),
    .din42_WIDTH( 18 ),
    .din43_WIDTH( 18 ),
    .din44_WIDTH( 18 ),
    .din45_WIDTH( 18 ),
    .din46_WIDTH( 18 ),
    .din47_WIDTH( 18 ),
    .din48_WIDTH( 18 ),
    .din49_WIDTH( 18 ),
    .din50_WIDTH( 18 ),
    .din51_WIDTH( 18 ),
    .din52_WIDTH( 18 ),
    .din53_WIDTH( 18 ),
    .din54_WIDTH( 18 ),
    .din55_WIDTH( 18 ),
    .din56_WIDTH( 18 ),
    .din57_WIDTH( 18 ),
    .din58_WIDTH( 18 ),
    .din59_WIDTH( 18 ),
    .din60_WIDTH( 18 ),
    .din61_WIDTH( 18 ),
    .din62_WIDTH( 18 ),
    .din63_WIDTH( 18 ),
    .din64_WIDTH( 18 ),
    .din65_WIDTH( 18 ),
    .din66_WIDTH( 18 ),
    .din67_WIDTH( 18 ),
    .din68_WIDTH( 18 ),
    .din69_WIDTH( 18 ),
    .din70_WIDTH( 18 ),
    .din71_WIDTH( 18 ),
    .din72_WIDTH( 18 ),
    .din73_WIDTH( 18 ),
    .din74_WIDTH( 18 ),
    .din75_WIDTH( 18 ),
    .din76_WIDTH( 18 ),
    .din77_WIDTH( 18 ),
    .din78_WIDTH( 18 ),
    .din79_WIDTH( 18 ),
    .din80_WIDTH( 18 ),
    .din81_WIDTH( 18 ),
    .din82_WIDTH( 18 ),
    .din83_WIDTH( 18 ),
    .din84_WIDTH( 18 ),
    .din85_WIDTH( 18 ),
    .din86_WIDTH( 18 ),
    .din87_WIDTH( 18 ),
    .din88_WIDTH( 18 ),
    .din89_WIDTH( 18 ),
    .din90_WIDTH( 18 ),
    .din91_WIDTH( 18 ),
    .din92_WIDTH( 18 ),
    .din93_WIDTH( 18 ),
    .din94_WIDTH( 18 ),
    .din95_WIDTH( 18 ),
    .din96_WIDTH( 18 ),
    .din97_WIDTH( 18 ),
    .din98_WIDTH( 18 ),
    .din99_WIDTH( 18 ),
    .din100_WIDTH( 18 ),
    .din101_WIDTH( 18 ),
    .din102_WIDTH( 18 ),
    .din103_WIDTH( 18 ),
    .din104_WIDTH( 18 ),
    .din105_WIDTH( 18 ),
    .din106_WIDTH( 18 ),
    .din107_WIDTH( 18 ),
    .din108_WIDTH( 18 ),
    .din109_WIDTH( 18 ),
    .din110_WIDTH( 18 ),
    .din111_WIDTH( 18 ),
    .din112_WIDTH( 18 ),
    .din113_WIDTH( 18 ),
    .din114_WIDTH( 18 ),
    .din115_WIDTH( 18 ),
    .din116_WIDTH( 18 ),
    .din117_WIDTH( 18 ),
    .din118_WIDTH( 18 ),
    .din119_WIDTH( 18 ),
    .din120_WIDTH( 18 ),
    .din121_WIDTH( 18 ),
    .din122_WIDTH( 18 ),
    .din123_WIDTH( 18 ),
    .din124_WIDTH( 18 ),
    .din125_WIDTH( 18 ),
    .din126_WIDTH( 18 ),
    .din127_WIDTH( 18 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
my_NN_mux_1287_18bkb_U4(
    .din0(my_NN_tanh_0_V),
    .din1(my_NN_tanh_1_V),
    .din2(my_NN_tanh_2_V),
    .din3(my_NN_tanh_3_V),
    .din4(my_NN_tanh_4_V),
    .din5(my_NN_tanh_5_V),
    .din6(my_NN_tanh_6_V),
    .din7(my_NN_tanh_7_V),
    .din8(my_NN_tanh_8_V),
    .din9(my_NN_tanh_9_V),
    .din10(my_NN_tanh_10_V),
    .din11(my_NN_tanh_11_V),
    .din12(my_NN_tanh_12_V),
    .din13(my_NN_tanh_13_V),
    .din14(my_NN_tanh_14_V),
    .din15(my_NN_tanh_15_V),
    .din16(my_NN_tanh_16_V),
    .din17(my_NN_tanh_17_V),
    .din18(my_NN_tanh_18_V),
    .din19(my_NN_tanh_19_V),
    .din20(my_NN_tanh_20_V),
    .din21(my_NN_tanh_21_V),
    .din22(my_NN_tanh_22_V),
    .din23(my_NN_tanh_23_V),
    .din24(my_NN_tanh_24_V),
    .din25(my_NN_tanh_25_V),
    .din26(my_NN_tanh_26_V),
    .din27(my_NN_tanh_27_V),
    .din28(my_NN_tanh_28_V),
    .din29(my_NN_tanh_29_V),
    .din30(my_NN_tanh_30_V),
    .din31(my_NN_tanh_31_V),
    .din32(my_NN_tanh_32_V),
    .din33(my_NN_tanh_33_V),
    .din34(my_NN_tanh_34_V),
    .din35(my_NN_tanh_35_V),
    .din36(my_NN_tanh_36_V),
    .din37(my_NN_tanh_37_V),
    .din38(my_NN_tanh_38_V),
    .din39(my_NN_tanh_39_V),
    .din40(my_NN_tanh_40_V),
    .din41(my_NN_tanh_41_V),
    .din42(my_NN_tanh_42_V),
    .din43(my_NN_tanh_43_V),
    .din44(my_NN_tanh_44_V),
    .din45(my_NN_tanh_45_V),
    .din46(my_NN_tanh_46_V),
    .din47(my_NN_tanh_47_V),
    .din48(my_NN_tanh_48_V),
    .din49(my_NN_tanh_49_V),
    .din50(my_NN_tanh_50_V),
    .din51(my_NN_tanh_51_V),
    .din52(my_NN_tanh_52_V),
    .din53(my_NN_tanh_53_V),
    .din54(my_NN_tanh_54_V),
    .din55(my_NN_tanh_55_V),
    .din56(my_NN_tanh_56_V),
    .din57(my_NN_tanh_57_V),
    .din58(my_NN_tanh_58_V),
    .din59(my_NN_tanh_59_V),
    .din60(my_NN_tanh_60_V),
    .din61(my_NN_tanh_61_V),
    .din62(my_NN_tanh_62_V),
    .din63(my_NN_tanh_63_V),
    .din64(my_NN_tanh_64_V),
    .din65(my_NN_tanh_65_V),
    .din66(my_NN_tanh_66_V),
    .din67(my_NN_tanh_67_V),
    .din68(my_NN_tanh_68_V),
    .din69(my_NN_tanh_69_V),
    .din70(my_NN_tanh_70_V),
    .din71(my_NN_tanh_71_V),
    .din72(my_NN_tanh_72_V),
    .din73(my_NN_tanh_73_V),
    .din74(my_NN_tanh_74_V),
    .din75(my_NN_tanh_75_V),
    .din76(my_NN_tanh_76_V),
    .din77(my_NN_tanh_77_V),
    .din78(my_NN_tanh_78_V),
    .din79(my_NN_tanh_79_V),
    .din80(my_NN_tanh_80_V),
    .din81(my_NN_tanh_81_V),
    .din82(my_NN_tanh_82_V),
    .din83(my_NN_tanh_83_V),
    .din84(my_NN_tanh_84_V),
    .din85(my_NN_tanh_85_V),
    .din86(my_NN_tanh_86_V),
    .din87(my_NN_tanh_87_V),
    .din88(my_NN_tanh_88_V),
    .din89(my_NN_tanh_89_V),
    .din90(my_NN_tanh_90_V),
    .din91(my_NN_tanh_91_V),
    .din92(my_NN_tanh_92_V),
    .din93(my_NN_tanh_93_V),
    .din94(my_NN_tanh_94_V),
    .din95(my_NN_tanh_95_V),
    .din96(my_NN_tanh_96_V),
    .din97(my_NN_tanh_97_V),
    .din98(my_NN_tanh_98_V),
    .din99(my_NN_tanh_99_V),
    .din100(my_NN_tanh_100_V),
    .din101(my_NN_tanh_101_V),
    .din102(my_NN_tanh_102_V),
    .din103(my_NN_tanh_103_V),
    .din104(my_NN_tanh_104_V),
    .din105(my_NN_tanh_105_V),
    .din106(my_NN_tanh_106_V),
    .din107(my_NN_tanh_107_V),
    .din108(my_NN_tanh_108_V),
    .din109(my_NN_tanh_109_V),
    .din110(my_NN_tanh_110_V),
    .din111(my_NN_tanh_111_V),
    .din112(my_NN_tanh_112_V),
    .din113(my_NN_tanh_113_V),
    .din114(my_NN_tanh_114_V),
    .din115(my_NN_tanh_115_V),
    .din116(my_NN_tanh_116_V),
    .din117(my_NN_tanh_117_V),
    .din118(my_NN_tanh_118_V),
    .din119(my_NN_tanh_119_V),
    .din120(my_NN_tanh_120_V),
    .din121(my_NN_tanh_121_V),
    .din122(my_NN_tanh_122_V),
    .din123(my_NN_tanh_123_V),
    .din124(my_NN_tanh_124_V),
    .din125(my_NN_tanh_125_V),
    .din126(my_NN_tanh_126_V),
    .din127(my_NN_tanh_127_V),
    .din128(p_Val2_55_fu_3355_p129),
    .dout(p_Val2_55_fu_3355_p130)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U5(
    .din0(newSel2_fu_1873_p3),
    .din1(p_Val2_s_fu_3764_p1),
    .dout(p_Val2_s_fu_3764_p2)
);

my_NN_mac_muladd_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 37 ))
my_NN_mac_muladd_dEe_U6(
    .din0(newSel5_fu_1905_p3),
    .din1(grp_fu_3771_p1),
    .din2(p_Val2_s_fu_3764_p2),
    .dout(grp_fu_3771_p3)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U7(
    .din0(newSel8_fu_1940_p3),
    .din1(p_Val2_12_fu_3780_p1),
    .dout(p_Val2_12_fu_3780_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U8(
    .din0(newSel11_fu_1984_p3),
    .din1(p_Val2_13_fu_3787_p1),
    .dout(p_Val2_13_fu_3787_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U9(
    .din0(p_Val2_19_fu_3794_p0),
    .din1(newSel14_fu_2025_p3),
    .dout(p_Val2_19_fu_3794_p2)
);

my_NN_mac_muladd_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 37 ))
my_NN_mac_muladd_dEe_U10(
    .din0(grp_fu_3801_p0),
    .din1(newSel17_fu_2053_p3),
    .din2(p_Val2_19_fu_3794_p2),
    .dout(grp_fu_3801_p3)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U11(
    .din0(p_Val2_20_fu_3810_p0),
    .din1(newSel20_fu_2084_p3),
    .dout(p_Val2_20_fu_3810_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U12(
    .din0(p_Val2_22_fu_3817_p0),
    .din1(newSel23_fu_2124_p3),
    .dout(p_Val2_22_fu_3817_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U13(
    .din0(p_Val2_26_fu_3824_p0),
    .din1(newSel26_fu_2161_p3),
    .dout(p_Val2_26_fu_3824_p2)
);

my_NN_mac_muladd_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 37 ))
my_NN_mac_muladd_dEe_U14(
    .din0(grp_fu_3831_p0),
    .din1(newSel29_fu_2189_p3),
    .din2(p_Val2_26_fu_3824_p2),
    .dout(grp_fu_3831_p3)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U15(
    .din0(p_Val2_27_fu_3840_p0),
    .din1(newSel32_fu_2220_p3),
    .dout(p_Val2_27_fu_3840_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U16(
    .din0(p_Val2_29_fu_3847_p0),
    .din1(newSel35_fu_2260_p3),
    .dout(p_Val2_29_fu_3847_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U17(
    .din0(p_Val2_33_fu_3854_p0),
    .din1(newSel38_fu_2297_p3),
    .dout(p_Val2_33_fu_3854_p2)
);

my_NN_mac_muladd_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 37 ))
my_NN_mac_muladd_dEe_U18(
    .din0(grp_fu_3861_p0),
    .din1(newSel41_fu_2325_p3),
    .din2(p_Val2_33_fu_3854_p2),
    .dout(grp_fu_3861_p3)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U19(
    .din0(p_Val2_34_fu_3870_p0),
    .din1(newSel44_fu_2356_p3),
    .dout(p_Val2_34_fu_3870_p2)
);

my_NN_mul_mul_18scud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
my_NN_mul_mul_18scud_U20(
    .din0(newSel47_fu_2396_p3),
    .din1(p_Val2_36_fu_3877_p1),
    .dout(p_Val2_36_fu_3877_p2)
);

my_NN_mac_muladd_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_eOg_U21(
    .din0(my_NN_b_0_V),
    .din1(grp_fu_3884_p1),
    .din2(grp_fu_3884_p2),
    .dout(grp_fu_3884_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U22(
    .din0(my_NN_b_4_V),
    .din1(grp_fu_3892_p1),
    .din2(grp_fu_3884_p3),
    .dout(grp_fu_3892_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U23(
    .din0(my_NN_b_8_V),
    .din1(grp_fu_3900_p1),
    .din2(grp_fu_3892_p3),
    .dout(grp_fu_3900_p3)
);

my_NN_mac_muladd_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_eOg_U24(
    .din0(my_NN_b_1_V),
    .din1(grp_fu_3909_p1),
    .din2(grp_fu_3909_p2),
    .dout(grp_fu_3909_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U25(
    .din0(my_NN_b_5_V),
    .din1(grp_fu_3917_p1),
    .din2(grp_fu_3909_p3),
    .dout(grp_fu_3917_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U26(
    .din0(my_NN_b_9_V),
    .din1(grp_fu_3925_p1),
    .din2(grp_fu_3917_p3),
    .dout(grp_fu_3925_p3)
);

my_NN_mac_muladd_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_eOg_U27(
    .din0(my_NN_b_2_V),
    .din1(grp_fu_3934_p1),
    .din2(grp_fu_3934_p2),
    .dout(grp_fu_3934_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U28(
    .din0(my_NN_b_6_V),
    .din1(grp_fu_3942_p1),
    .din2(grp_fu_3934_p3),
    .dout(grp_fu_3942_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U29(
    .din0(my_NN_b_10_V),
    .din1(grp_fu_3950_p1),
    .din2(grp_fu_3942_p3),
    .dout(grp_fu_3950_p3)
);

my_NN_mac_muladd_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_eOg_U30(
    .din0(my_NN_b_3_V),
    .din1(grp_fu_3959_p1),
    .din2(grp_fu_3959_p2),
    .dout(grp_fu_3959_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U31(
    .din0(my_NN_b_7_V),
    .din1(grp_fu_3967_p1),
    .din2(grp_fu_3959_p3),
    .dout(grp_fu_3967_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U32(
    .din0(my_NN_b_11_V),
    .din1(grp_fu_3975_p1),
    .din2(grp_fu_3967_p3),
    .dout(grp_fu_3975_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U33(
    .din0(grp_fu_3984_p0),
    .din1(my_NN_b_0_V),
    .din2(tmp_22_fu_3991_p2),
    .dout(grp_fu_3984_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U34(
    .din0(tmp_22_fu_3991_p0),
    .din1(my_NN_b_4_V),
    .dout(tmp_22_fu_3991_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U35(
    .din0(grp_fu_3998_p0),
    .din1(my_NN_b_8_V),
    .din2(grp_fu_3984_p3),
    .dout(grp_fu_3998_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U36(
    .din0(grp_fu_4007_p0),
    .din1(my_NN_b_1_V),
    .din2(tmp_28_fu_4014_p2),
    .dout(grp_fu_4007_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U37(
    .din0(tmp_28_fu_4014_p0),
    .din1(my_NN_b_5_V),
    .dout(tmp_28_fu_4014_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U38(
    .din0(grp_fu_4021_p0),
    .din1(my_NN_b_9_V),
    .din2(grp_fu_4007_p3),
    .dout(grp_fu_4021_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U39(
    .din0(grp_fu_4030_p0),
    .din1(my_NN_b_2_V),
    .din2(tmp_33_fu_4037_p2),
    .dout(grp_fu_4030_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U40(
    .din0(tmp_33_fu_4037_p0),
    .din1(my_NN_b_6_V),
    .dout(tmp_33_fu_4037_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U41(
    .din0(grp_fu_4044_p0),
    .din1(my_NN_b_10_V),
    .din2(grp_fu_4030_p3),
    .dout(grp_fu_4044_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U42(
    .din0(grp_fu_4053_p0),
    .din1(my_NN_b_3_V),
    .din2(tmp_38_fu_4060_p2),
    .dout(grp_fu_4053_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U43(
    .din0(tmp_38_fu_4060_p0),
    .din1(my_NN_b_7_V),
    .dout(tmp_38_fu_4060_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U44(
    .din0(grp_fu_4067_p0),
    .din1(my_NN_b_11_V),
    .din2(grp_fu_4053_p3),
    .dout(grp_fu_4067_p3)
);

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        my_NN_n_V_o_ap_vld = 1'b1;
    end else begin
        my_NN_n_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((tmp_16_fu_2417_p2 == 1'd1)) begin
            x0_o = {{grp_fu_3998_p3[29:12]}};
        end else if ((tmp_16_fu_2417_p2 == 1'd0)) begin
            x0_o = {{grp_fu_3900_p3[29:12]}};
        end else begin
            x0_o = 'bx;
        end
    end else begin
        x0_o = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_16_fu_2417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_16_fu_2417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        x0_o_ap_vld = 1'b1;
    end else begin
        x0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((tmp_16_fu_2417_p2 == 1'd1)) begin
            x1_o = {{grp_fu_4021_p3[29:12]}};
        end else if ((tmp_16_fu_2417_p2 == 1'd0)) begin
            x1_o = {{grp_fu_3925_p3[29:12]}};
        end else begin
            x1_o = 'bx;
        end
    end else begin
        x1_o = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_16_fu_2417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_16_fu_2417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        x1_o_ap_vld = 1'b1;
    end else begin
        x1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((tmp_16_fu_2417_p2 == 1'd1)) begin
            x2_o = {{grp_fu_4044_p3[29:12]}};
        end else if ((tmp_16_fu_2417_p2 == 1'd0)) begin
            x2_o = {{grp_fu_3950_p3[29:12]}};
        end else begin
            x2_o = 'bx;
        end
    end else begin
        x2_o = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_16_fu_2417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_16_fu_2417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        x2_o_ap_vld = 1'b1;
    end else begin
        x2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((tmp_16_fu_2417_p2 == 1'd1)) begin
            x3_o = {{grp_fu_4067_p3[29:12]}};
        end else if ((tmp_16_fu_2417_p2 == 1'd0)) begin
            x3_o = {{grp_fu_3975_p3[29:12]}};
        end else begin
            x3_o = 'bx;
        end
    end else begin
        x3_o = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_16_fu_2417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_16_fu_2417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        x3_o_ap_vld = 1'b1;
    end else begin
        x3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP2_V_1_fu_1917_p0 = x1_i;

assign OP2_V_1_fu_1917_p1 = OP2_V_1_fu_1917_p0;

assign OP2_V_2_fu_1952_p0 = x2_i;

assign OP2_V_2_fu_1952_p1 = OP2_V_2_fu_1952_p0;

assign OP2_V_3_fu_1996_p0 = x3_i;

assign OP2_V_3_fu_1996_p1 = OP2_V_3_fu_1996_p0;

assign OP2_V_fu_1885_p0 = x0_i;

assign OP2_V_fu_1885_p1 = OP2_V_fu_1885_p0;

assign ap_CS_fsm = ap_ST_fsm_state1;

assign ap_CS_fsm_state1 = ap_ST_fsm_state1[32'd0];

assign grp_fu_3771_p1 = OP2_V_1_fu_1917_p1;

assign grp_fu_3801_p0 = OP2_V_1_fu_1917_p1;

assign grp_fu_3831_p0 = OP2_V_1_fu_1917_p1;

assign grp_fu_3861_p0 = OP2_V_1_fu_1917_p1;

assign grp_fu_3884_p1 = tmp_41_fu_2437_p1;

assign grp_fu_3884_p2 = {{p_Val2_46_fu_2441_p130}, {12'd0}};

assign grp_fu_3892_p1 = tmp_45_fu_2715_p1;

assign grp_fu_3900_p1 = tmp_49_fu_2723_p1;

assign grp_fu_3909_p1 = tmp_41_fu_2437_p1;

assign grp_fu_3909_p2 = {{p_Val2_49_fu_2751_p130}, {12'd0}};

assign grp_fu_3917_p1 = tmp_45_fu_2715_p1;

assign grp_fu_3925_p1 = tmp_49_fu_2723_p1;

assign grp_fu_3934_p1 = tmp_41_fu_2437_p1;

assign grp_fu_3934_p2 = {{p_Val2_52_fu_3053_p130}, {12'd0}};

assign grp_fu_3942_p1 = tmp_45_fu_2715_p1;

assign grp_fu_3950_p1 = tmp_49_fu_2723_p1;

assign grp_fu_3959_p1 = tmp_41_fu_2437_p1;

assign grp_fu_3959_p2 = {{p_Val2_55_fu_3355_p130}, {12'd0}};

assign grp_fu_3967_p1 = tmp_45_fu_2715_p1;

assign grp_fu_3975_p1 = tmp_49_fu_2723_p1;

assign grp_fu_3984_p0 = tmp_17_fu_3643_p1;

assign grp_fu_3998_p0 = tmp_23_fu_3659_p1;

assign grp_fu_4007_p0 = tmp_17_fu_3643_p1;

assign grp_fu_4021_p0 = tmp_23_fu_3659_p1;

assign grp_fu_4030_p0 = tmp_17_fu_3643_p1;

assign grp_fu_4044_p0 = tmp_23_fu_3659_p1;

assign grp_fu_4053_p0 = tmp_17_fu_3643_p1;

assign grp_fu_4067_p0 = tmp_23_fu_3659_p1;

assign my_NN_n_V_o = ((tmp_71_fu_3743_p2[0:0] === 1'b1) ? 3'd0 : tmp_72_fu_3749_p2);

assign newSel10_fu_1976_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_12_V : my_NN_w_60_V);

assign newSel11_fu_1984_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel9_fu_1968_p3 : newSel10_fu_1976_p3);

assign newSel12_fu_2009_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_33_V : my_NN_w_17_V);

assign newSel13_fu_2017_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_1_V : my_NN_w_49_V);

assign newSel14_fu_2025_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel12_fu_2009_p3 : newSel13_fu_2017_p3);

assign newSel15_fu_2037_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_37_V : my_NN_w_21_V);

assign newSel16_fu_2045_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_5_V : my_NN_w_53_V);

assign newSel17_fu_2053_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel15_fu_2037_p3 : newSel16_fu_2045_p3);

assign newSel18_fu_2068_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_41_V : my_NN_w_25_V);

assign newSel19_fu_2076_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_9_V : my_NN_w_57_V);

assign newSel1_fu_1865_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_0_V : my_NN_w_48_V);

assign newSel20_fu_2084_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel18_fu_2068_p3 : newSel19_fu_2076_p3);

assign newSel21_fu_2108_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_45_V : my_NN_w_29_V);

assign newSel22_fu_2116_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_13_V : my_NN_w_61_V);

assign newSel23_fu_2124_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel21_fu_2108_p3 : newSel22_fu_2116_p3);

assign newSel24_fu_2145_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_34_V : my_NN_w_18_V);

assign newSel25_fu_2153_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_2_V : my_NN_w_50_V);

assign newSel26_fu_2161_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel24_fu_2145_p3 : newSel25_fu_2153_p3);

assign newSel27_fu_2173_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_38_V : my_NN_w_22_V);

assign newSel28_fu_2181_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_6_V : my_NN_w_54_V);

assign newSel29_fu_2189_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel27_fu_2173_p3 : newSel28_fu_2181_p3);

assign newSel2_fu_1873_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel_fu_1851_p3 : newSel1_fu_1865_p3);

assign newSel30_fu_2204_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_42_V : my_NN_w_26_V);

assign newSel31_fu_2212_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_10_V : my_NN_w_58_V);

assign newSel32_fu_2220_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel30_fu_2204_p3 : newSel31_fu_2212_p3);

assign newSel33_fu_2244_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_46_V : my_NN_w_30_V);

assign newSel34_fu_2252_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_14_V : my_NN_w_62_V);

assign newSel35_fu_2260_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel33_fu_2244_p3 : newSel34_fu_2252_p3);

assign newSel36_fu_2281_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_35_V : my_NN_w_19_V);

assign newSel37_fu_2289_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_3_V : my_NN_w_51_V);

assign newSel38_fu_2297_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel36_fu_2281_p3 : newSel37_fu_2289_p3);

assign newSel39_fu_2309_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_39_V : my_NN_w_23_V);

assign newSel3_fu_1889_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_36_V : my_NN_w_20_V);

assign newSel40_fu_2317_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_7_V : my_NN_w_55_V);

assign newSel41_fu_2325_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel39_fu_2309_p3 : newSel40_fu_2317_p3);

assign newSel42_fu_2340_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_43_V : my_NN_w_27_V);

assign newSel43_fu_2348_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_11_V : my_NN_w_59_V);

assign newSel44_fu_2356_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel42_fu_2340_p3 : newSel43_fu_2348_p3);

assign newSel45_fu_2380_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_47_V : my_NN_w_31_V);

assign newSel46_fu_2388_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_15_V : my_NN_w_63_V);

assign newSel47_fu_2396_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel45_fu_2380_p3 : newSel46_fu_2388_p3);

assign newSel4_fu_1897_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_4_V : my_NN_w_52_V);

assign newSel5_fu_1905_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel3_fu_1889_p3 : newSel4_fu_1897_p3);

assign newSel6_fu_1924_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_40_V : my_NN_w_24_V);

assign newSel7_fu_1932_p3 = ((sel_tmp_fu_1833_p2[0:0] === 1'b1) ? my_NN_w_8_V : my_NN_w_56_V);

assign newSel8_fu_1940_p3 = ((or_cond_fu_1859_p2[0:0] === 1'b1) ? newSel6_fu_1924_p3 : newSel7_fu_1932_p3);

assign newSel9_fu_1968_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_44_V : my_NN_w_28_V);

assign newSel_fu_1851_p3 = ((sel_tmp5_fu_1845_p2[0:0] === 1'b1) ? my_NN_w_32_V : my_NN_w_16_V);

assign or_cond_fu_1859_p2 = (sel_tmp5_fu_1845_p2 | sel_tmp3_fu_1839_p2);

assign p_Val2_12_fu_3780_p1 = OP2_V_2_fu_1952_p1;

assign p_Val2_13_fu_3787_p1 = OP2_V_3_fu_1996_p1;

assign p_Val2_16_fu_1962_p2 = (tmp_2_fu_1956_p1 + tmp_3_fu_1959_p1);

assign p_Val2_17_fu_2003_p2 = (p_Val2_16_fu_1962_p2 + tmp_17_cast_fu_2000_p1);

assign p_Val2_19_fu_3794_p0 = OP2_V_fu_1885_p1;

assign p_Val2_20_fu_3810_p0 = OP2_V_2_fu_1952_p1;

assign p_Val2_22_fu_3817_p0 = OP2_V_3_fu_1996_p1;

assign p_Val2_23_fu_2102_p2 = (tmp_6_fu_2096_p1 + tmp_7_fu_2099_p1);

assign p_Val2_24_fu_2139_p2 = (p_Val2_23_fu_2102_p2 + tmp_23_cast_fu_2136_p1);

assign p_Val2_26_fu_3824_p0 = OP2_V_fu_1885_p1;

assign p_Val2_27_fu_3840_p0 = OP2_V_2_fu_1952_p1;

assign p_Val2_29_fu_3847_p0 = OP2_V_3_fu_1996_p1;

assign p_Val2_30_fu_2238_p2 = (tmp_10_fu_2232_p1 + tmp_11_fu_2235_p1);

assign p_Val2_31_fu_2275_p2 = (p_Val2_30_fu_2238_p2 + tmp_29_cast_fu_2272_p1);

assign p_Val2_33_fu_3854_p0 = OP2_V_fu_1885_p1;

assign p_Val2_34_fu_3870_p0 = OP2_V_2_fu_1952_p1;

assign p_Val2_36_fu_3877_p1 = OP2_V_3_fu_1996_p1;

assign p_Val2_37_fu_2374_p2 = (tmp_14_fu_2368_p1 + tmp_15_fu_2371_p1);

assign p_Val2_38_fu_2411_p2 = (p_Val2_37_fu_2374_p2 + tmp_35_cast_fu_2408_p1);

assign p_Val2_46_fu_2441_p129 = {{p_Val2_17_fu_2003_p2[29:23]}};

assign p_Val2_49_fu_2751_p129 = {{p_Val2_24_fu_2139_p2[29:23]}};

assign p_Val2_52_fu_3053_p129 = {{p_Val2_31_fu_2275_p2[29:23]}};

assign p_Val2_55_fu_3355_p129 = {{p_Val2_38_fu_2411_p2[29:23]}};

assign p_Val2_s_fu_3764_p1 = OP2_V_fu_1885_p1;

assign sel_tmp3_fu_1839_p2 = ((tmp_73_fu_1829_p1 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_1845_p2 = ((tmp_73_fu_1829_p1 == 2'd2) ? 1'b1 : 1'b0);

assign sel_tmp_fu_1833_p2 = ((tmp_73_fu_1829_p1 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_10_fu_2232_p1 = $unsigned(grp_fu_3831_p3);

assign tmp_11_fu_2235_p1 = $unsigned(p_Val2_27_fu_3840_p2);

assign tmp_14_fu_2368_p1 = $unsigned(grp_fu_3861_p3);

assign tmp_15_fu_2371_p1 = $unsigned(p_Val2_34_fu_3870_p2);

assign tmp_16_fu_2417_p2 = ((my_NN_n_V_i == 3'd0) ? 1'b1 : 1'b0);

assign tmp_17_cast_fu_2000_p1 = $unsigned(p_Val2_13_fu_3787_p2);

assign tmp_17_fu_3643_p0 = U0;

assign tmp_17_fu_3643_p1 = tmp_17_fu_3643_p0;

assign tmp_19_fu_3651_p0 = U1;

assign tmp_19_fu_3651_p1 = tmp_19_fu_3651_p0;

assign tmp_22_fu_3991_p0 = tmp_19_fu_3651_p1;

assign tmp_23_cast_fu_2136_p1 = $unsigned(p_Val2_22_fu_3817_p2);

assign tmp_23_fu_3659_p0 = U2;

assign tmp_23_fu_3659_p1 = tmp_23_fu_3659_p0;

assign tmp_28_fu_4014_p0 = tmp_19_fu_3651_p1;

assign tmp_29_cast_fu_2272_p1 = $unsigned(p_Val2_29_fu_3847_p2);

assign tmp_2_fu_1956_p1 = $unsigned(grp_fu_3771_p3);

assign tmp_33_fu_4037_p0 = tmp_19_fu_3651_p1;

assign tmp_35_cast_fu_2408_p1 = $unsigned(p_Val2_36_fu_3877_p2);

assign tmp_38_fu_4060_p0 = tmp_19_fu_3651_p1;

assign tmp_3_fu_1959_p1 = $unsigned(p_Val2_12_fu_3780_p2);

assign tmp_41_fu_2437_p0 = U0;

assign tmp_41_fu_2437_p1 = tmp_41_fu_2437_p0;

assign tmp_45_fu_2715_p0 = U1;

assign tmp_45_fu_2715_p1 = tmp_45_fu_2715_p0;

assign tmp_49_fu_2723_p0 = U2;

assign tmp_49_fu_2723_p1 = tmp_49_fu_2723_p0;

assign tmp_6_fu_2096_p1 = $unsigned(grp_fu_3801_p3);

assign tmp_71_fu_3743_p2 = ((my_NN_n_V_i == 3'd3) ? 1'b1 : 1'b0);

assign tmp_72_fu_3749_p2 = (my_NN_n_V_i + 3'd1);

assign tmp_73_fu_1829_p1 = my_NN_n_V_i[1:0];

assign tmp_7_fu_2099_p1 = $unsigned(p_Val2_20_fu_3810_p2);

endmodule //my_NN_NN_func
