-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity my_NN is
port (
    U0 : IN STD_LOGIC_VECTOR (17 downto 0);
    U1 : IN STD_LOGIC_VECTOR (17 downto 0);
    U2 : IN STD_LOGIC_VECTOR (17 downto 0);
    CLK : IN STD_LOGIC;
    Y0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    Y1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of my_NN is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "my_NN,hls_ip_2018_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100ffg1156-1,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=29.931000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=48,HLS_SYN_FF=75,HLS_SYN_LUT=4025}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv18_3EB : STD_LOGIC_VECTOR (17 downto 0) := "000000001111101011";
    constant ap_const_lv18_764 : STD_LOGIC_VECTOR (17 downto 0) := "000000011101100100";
    constant ap_const_lv18_A29 : STD_LOGIC_VECTOR (17 downto 0) := "000000101000101001";
    constant ap_const_lv18_C2F : STD_LOGIC_VECTOR (17 downto 0) := "000000110000101111";
    constant ap_const_lv18_D92 : STD_LOGIC_VECTOR (17 downto 0) := "000000110110010010";
    constant ap_const_lv18_E7B : STD_LOGIC_VECTOR (17 downto 0) := "000000111001111011";
    constant ap_const_lv18_F0F : STD_LOGIC_VECTOR (17 downto 0) := "000000111100001111";
    constant ap_const_lv18_F6C : STD_LOGIC_VECTOR (17 downto 0) := "000000111101101100";
    constant ap_const_lv18_FA5 : STD_LOGIC_VECTOR (17 downto 0) := "000000111110100101";
    constant ap_const_lv18_FC9 : STD_LOGIC_VECTOR (17 downto 0) := "000000111111001001";
    constant ap_const_lv18_FDE : STD_LOGIC_VECTOR (17 downto 0) := "000000111111011110";
    constant ap_const_lv18_FEB : STD_LOGIC_VECTOR (17 downto 0) := "000000111111101011";
    constant ap_const_lv18_FF3 : STD_LOGIC_VECTOR (17 downto 0) := "000000111111110011";
    constant ap_const_lv18_FF8 : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111000";
    constant ap_const_lv18_FFB : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111011";
    constant ap_const_lv18_FFD : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111101";
    constant ap_const_lv18_FFE : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111110";
    constant ap_const_lv18_FFF : STD_LOGIC_VECTOR (17 downto 0) := "000000111111111111";
    constant ap_const_lv18_1000 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_const_lv18_9925 : STD_LOGIC_VECTOR (17 downto 0) := "001001100100100101";
    constant ap_const_lv18_4DA8 : STD_LOGIC_VECTOR (17 downto 0) := "000100110110101000";
    constant ap_const_lv18_800B : STD_LOGIC_VECTOR (17 downto 0) := "001000000000001011";
    constant ap_const_lv18_16B3 : STD_LOGIC_VECTOR (17 downto 0) := "000001011010110011";
    constant ap_const_lv18_437B : STD_LOGIC_VECTOR (17 downto 0) := "000100001101111011";
    constant ap_const_lv18_9284 : STD_LOGIC_VECTOR (17 downto 0) := "001001001010000100";
    constant ap_const_lv18_7EC0 : STD_LOGIC_VECTOR (17 downto 0) := "000111111011000000";
    constant ap_const_lv18_9984 : STD_LOGIC_VECTOR (17 downto 0) := "001001100110000100";
    constant ap_const_lv18_68EB : STD_LOGIC_VECTOR (17 downto 0) := "000110100011101011";
    constant ap_const_lv18_5B6 : STD_LOGIC_VECTOR (17 downto 0) := "000000010110110110";
    constant ap_const_lv18_87DC : STD_LOGIC_VECTOR (17 downto 0) := "001000011111011100";
    constant ap_const_lv18_9570 : STD_LOGIC_VECTOR (17 downto 0) := "001001010101110000";
    constant ap_const_lv18_6C98 : STD_LOGIC_VECTOR (17 downto 0) := "000110110010011000";
    constant ap_const_lv18_793D : STD_LOGIC_VECTOR (17 downto 0) := "000111100100111101";
    constant ap_const_lv18_76E6 : STD_LOGIC_VECTOR (17 downto 0) := "000111011011100110";
    constant ap_const_lv18_3EC1 : STD_LOGIC_VECTOR (17 downto 0) := "000011111011000001";
    constant ap_const_lv18_68E0 : STD_LOGIC_VECTOR (17 downto 0) := "000110100011100000";
    constant ap_const_lv18_1B63 : STD_LOGIC_VECTOR (17 downto 0) := "000001101101100011";
    constant ap_const_lv18_70F7 : STD_LOGIC_VECTOR (17 downto 0) := "000111000011110111";
    constant ap_const_lv18_517 : STD_LOGIC_VECTOR (17 downto 0) := "000000010100010111";
    constant ap_const_lv18_2C4E : STD_LOGIC_VECTOR (17 downto 0) := "000010110001001110";
    constant ap_const_lv18_763 : STD_LOGIC_VECTOR (17 downto 0) := "000000011101100011";
    constant ap_const_lv18_F8A : STD_LOGIC_VECTOR (17 downto 0) := "000000111110001010";
    constant ap_const_lv18_83C0 : STD_LOGIC_VECTOR (17 downto 0) := "001000001111000000";
    constant ap_const_lv18_6F2C : STD_LOGIC_VECTOR (17 downto 0) := "000110111100101100";
    constant ap_const_lv18_32BC : STD_LOGIC_VECTOR (17 downto 0) := "000011001010111100";
    constant ap_const_lv18_9809 : STD_LOGIC_VECTOR (17 downto 0) := "001001100000001001";
    constant ap_const_lv18_582 : STD_LOGIC_VECTOR (17 downto 0) := "000000010110000010";
    constant ap_const_lv18_4632 : STD_LOGIC_VECTOR (17 downto 0) := "000100011000110010";
    constant ap_const_lv18_3D0C : STD_LOGIC_VECTOR (17 downto 0) := "000011110100001100";
    constant ap_const_lv18_7A7B : STD_LOGIC_VECTOR (17 downto 0) := "000111101001111011";
    constant ap_const_lv18_7F3B : STD_LOGIC_VECTOR (17 downto 0) := "000111111100111011";
    constant ap_const_lv18_1DE6 : STD_LOGIC_VECTOR (17 downto 0) := "000001110111100110";
    constant ap_const_lv18_4E5C : STD_LOGIC_VECTOR (17 downto 0) := "000100111001011100";
    constant ap_const_lv18_474B : STD_LOGIC_VECTOR (17 downto 0) := "000100011101001011";
    constant ap_const_lv18_6768 : STD_LOGIC_VECTOR (17 downto 0) := "000110011101101000";
    constant ap_const_lv18_717F : STD_LOGIC_VECTOR (17 downto 0) := "000111000101111111";
    constant ap_const_lv18_78BF : STD_LOGIC_VECTOR (17 downto 0) := "000111100010111111";
    constant ap_const_lv18_2C29 : STD_LOGIC_VECTOR (17 downto 0) := "000010110000101001";
    constant ap_const_lv18_6CC0 : STD_LOGIC_VECTOR (17 downto 0) := "000110110011000000";
    constant ap_const_lv18_68D0 : STD_LOGIC_VECTOR (17 downto 0) := "000110100011010000";
    constant ap_const_lv18_1A04 : STD_LOGIC_VECTOR (17 downto 0) := "000001101000000100";
    constant ap_const_lv18_130A : STD_LOGIC_VECTOR (17 downto 0) := "000001001100001010";
    constant ap_const_lv18_4FBC : STD_LOGIC_VECTOR (17 downto 0) := "000100111110111100";
    constant ap_const_lv18_998F : STD_LOGIC_VECTOR (17 downto 0) := "001001100110001111";
    constant ap_const_lv18_3676 : STD_LOGIC_VECTOR (17 downto 0) := "000011011001110110";
    constant ap_const_lv18_5DA4 : STD_LOGIC_VECTOR (17 downto 0) := "000101110110100100";
    constant ap_const_lv18_23CF : STD_LOGIC_VECTOR (17 downto 0) := "000010001111001111";
    constant ap_const_lv18_D09 : STD_LOGIC_VECTOR (17 downto 0) := "000000110100001001";
    constant ap_const_lv18_E7E : STD_LOGIC_VECTOR (17 downto 0) := "000000111001111110";
    constant ap_const_lv18_208 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000001000";
    constant ap_const_lv18_E9D : STD_LOGIC_VECTOR (17 downto 0) := "000000111010011101";
    constant ap_const_lv18_A1E : STD_LOGIC_VECTOR (17 downto 0) := "000000101000011110";
    constant ap_const_lv18_18F : STD_LOGIC_VECTOR (17 downto 0) := "000000000110001111";
    constant ap_const_lv18_474 : STD_LOGIC_VECTOR (17 downto 0) := "000000010001110100";
    constant ap_const_lv18_8C0 : STD_LOGIC_VECTOR (17 downto 0) := "000000100011000000";
    constant ap_const_lv18_F51 : STD_LOGIC_VECTOR (17 downto 0) := "000000111101010001";
    constant ap_const_lv18_F70 : STD_LOGIC_VECTOR (17 downto 0) := "000000111101110000";
    constant ap_const_lv18_285 : STD_LOGIC_VECTOR (17 downto 0) := "000000001010000101";
    constant ap_const_lv18_F87 : STD_LOGIC_VECTOR (17 downto 0) := "000000111110000111";
    constant ap_const_lv18_3C19 : STD_LOGIC_VECTOR (17 downto 0) := "000011110000011001";
    constant ap_const_lv18_4745 : STD_LOGIC_VECTOR (17 downto 0) := "000100011101000101";
    constant ap_const_lv18_1468 : STD_LOGIC_VECTOR (17 downto 0) := "000001010001101000";
    constant ap_const_lv18_4CBE : STD_LOGIC_VECTOR (17 downto 0) := "000100110010111110";
    constant ap_const_lv18_287A : STD_LOGIC_VECTOR (17 downto 0) := "000010100001111010";
    constant ap_const_lv18_2BC6 : STD_LOGIC_VECTOR (17 downto 0) := "000010101111000110";
    constant ap_const_lv18_37ED : STD_LOGIC_VECTOR (17 downto 0) := "000011011111101101";
    constant ap_const_lv18_B17 : STD_LOGIC_VECTOR (17 downto 0) := "000000101100010111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal my_NN_ssdm_thread_load_fu_3320_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal StgValue_231_my_NN_NN_func_fu_2420_x0_o : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld : STD_LOGIC;
    signal StgValue_231_my_NN_NN_func_fu_2420_x1_o : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld : STD_LOGIC;
    signal StgValue_231_my_NN_NN_func_fu_2420_x2_o : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld : STD_LOGIC;
    signal StgValue_231_my_NN_NN_func_fu_2420_x3_o : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld : STD_LOGIC;
    signal StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o : STD_LOGIC_VECTOR (2 downto 0);
    signal StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld : STD_LOGIC;
    signal StgValue_237_my_NN_out_func_fu_2870_Y0 : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld : STD_LOGIC;
    signal StgValue_237_my_NN_out_func_fu_2870_Y1 : STD_LOGIC_VECTOR (17 downto 0);
    signal StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal x0 : STD_LOGIC_VECTOR (17 downto 0);
    signal x1 : STD_LOGIC_VECTOR (17 downto 0);
    signal x2 : STD_LOGIC_VECTOR (17 downto 0);
    signal x3 : STD_LOGIC_VECTOR (17 downto 0);
    signal my_NN_n_V : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";

    component my_NN_NN_func IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        U0 : IN STD_LOGIC_VECTOR (17 downto 0);
        U1 : IN STD_LOGIC_VECTOR (17 downto 0);
        U2 : IN STD_LOGIC_VECTOR (17 downto 0);
        x0_i : IN STD_LOGIC_VECTOR (17 downto 0);
        x0_o : OUT STD_LOGIC_VECTOR (17 downto 0);
        x0_o_ap_vld : OUT STD_LOGIC;
        x1_i : IN STD_LOGIC_VECTOR (17 downto 0);
        x1_o : OUT STD_LOGIC_VECTOR (17 downto 0);
        x1_o_ap_vld : OUT STD_LOGIC;
        x2_i : IN STD_LOGIC_VECTOR (17 downto 0);
        x2_o : OUT STD_LOGIC_VECTOR (17 downto 0);
        x2_o_ap_vld : OUT STD_LOGIC;
        x3_i : IN STD_LOGIC_VECTOR (17 downto 0);
        x3_o : OUT STD_LOGIC_VECTOR (17 downto 0);
        x3_o_ap_vld : OUT STD_LOGIC;
        my_NN_tanh_0_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_1_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_2_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_3_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_4_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_5_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_6_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_7_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_8_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_9_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_10_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_11_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_12_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_13_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_14_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_15_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_16_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_17_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_18_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_19_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_20_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_21_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_22_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_23_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_24_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_25_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_26_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_27_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_28_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_29_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_30_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_31_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_32_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_33_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_34_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_35_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_36_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_37_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_38_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_39_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_40_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_41_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_42_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_43_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_44_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_45_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_46_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_47_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_48_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_49_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_50_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_51_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_52_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_53_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_54_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_55_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_56_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_57_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_58_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_59_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_60_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_61_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_62_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_63_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_64_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_65_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_66_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_67_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_68_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_69_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_70_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_71_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_72_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_73_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_74_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_75_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_76_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_77_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_78_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_79_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_80_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_81_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_82_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_83_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_84_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_85_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_86_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_87_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_88_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_89_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_90_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_91_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_92_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_93_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_94_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_95_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_96_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_97_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_98_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_99_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_100_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_101_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_102_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_103_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_104_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_105_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_106_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_107_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_108_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_109_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_110_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_111_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_112_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_113_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_114_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_115_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_116_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_117_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_118_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_119_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_120_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_121_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_122_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_123_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_124_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_125_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_126_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_tanh_127_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_0_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_1_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_2_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_3_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_4_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_5_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_6_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_7_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_8_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_9_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_10_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_b_11_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_0_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_1_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_2_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_3_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_4_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_5_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_6_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_7_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_8_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_9_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_10_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_11_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_12_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_13_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_14_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_15_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_16_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_17_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_18_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_19_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_20_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_21_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_22_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_23_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_24_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_25_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_26_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_27_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_28_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_29_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_30_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_31_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_32_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_33_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_34_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_35_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_36_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_37_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_38_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_39_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_40_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_41_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_42_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_43_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_44_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_45_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_46_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_47_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_48_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_49_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_50_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_51_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_52_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_53_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_54_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_55_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_56_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_57_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_58_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_59_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_60_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_61_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_62_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_w_63_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_n_V_i : IN STD_LOGIC_VECTOR (2 downto 0);
        my_NN_n_V_o : OUT STD_LOGIC_VECTOR (2 downto 0);
        my_NN_n_V_o_ap_vld : OUT STD_LOGIC );
    end component;


    component my_NN_out_func IS
    port (
        Y0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        Y0_ap_vld : OUT STD_LOGIC;
        Y1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        Y1_ap_vld : OUT STD_LOGIC;
        x0 : IN STD_LOGIC_VECTOR (17 downto 0);
        x1 : IN STD_LOGIC_VECTOR (17 downto 0);
        x2 : IN STD_LOGIC_VECTOR (17 downto 0);
        x3 : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_0_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_1_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_2_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_3_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_4_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_5_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_6_V : IN STD_LOGIC_VECTOR (17 downto 0);
        my_NN_c_7_V : IN STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    StgValue_231_my_NN_NN_func_fu_2420 : component my_NN_NN_func
    port map (
        ap_clk => CLK,
        ap_rst => ap_rst,
        U0 => U0,
        U1 => U1,
        U2 => U2,
        x0_i => x0,
        x0_o => StgValue_231_my_NN_NN_func_fu_2420_x0_o,
        x0_o_ap_vld => StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld,
        x1_i => x1,
        x1_o => StgValue_231_my_NN_NN_func_fu_2420_x1_o,
        x1_o_ap_vld => StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld,
        x2_i => x2,
        x2_o => StgValue_231_my_NN_NN_func_fu_2420_x2_o,
        x2_o_ap_vld => StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld,
        x3_i => x3,
        x3_o => StgValue_231_my_NN_NN_func_fu_2420_x3_o,
        x3_o_ap_vld => StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld,
        my_NN_tanh_0_V => ap_const_lv18_0,
        my_NN_tanh_1_V => ap_const_lv18_3EB,
        my_NN_tanh_2_V => ap_const_lv18_764,
        my_NN_tanh_3_V => ap_const_lv18_A29,
        my_NN_tanh_4_V => ap_const_lv18_C2F,
        my_NN_tanh_5_V => ap_const_lv18_D92,
        my_NN_tanh_6_V => ap_const_lv18_E7B,
        my_NN_tanh_7_V => ap_const_lv18_F0F,
        my_NN_tanh_8_V => ap_const_lv18_F6C,
        my_NN_tanh_9_V => ap_const_lv18_FA5,
        my_NN_tanh_10_V => ap_const_lv18_FC9,
        my_NN_tanh_11_V => ap_const_lv18_FDE,
        my_NN_tanh_12_V => ap_const_lv18_FEB,
        my_NN_tanh_13_V => ap_const_lv18_FF3,
        my_NN_tanh_14_V => ap_const_lv18_FF8,
        my_NN_tanh_15_V => ap_const_lv18_FFB,
        my_NN_tanh_16_V => ap_const_lv18_FFD,
        my_NN_tanh_17_V => ap_const_lv18_FFE,
        my_NN_tanh_18_V => ap_const_lv18_FFE,
        my_NN_tanh_19_V => ap_const_lv18_FFF,
        my_NN_tanh_20_V => ap_const_lv18_FFF,
        my_NN_tanh_21_V => ap_const_lv18_FFF,
        my_NN_tanh_22_V => ap_const_lv18_FFF,
        my_NN_tanh_23_V => ap_const_lv18_FFF,
        my_NN_tanh_24_V => ap_const_lv18_FFF,
        my_NN_tanh_25_V => ap_const_lv18_FFF,
        my_NN_tanh_26_V => ap_const_lv18_FFF,
        my_NN_tanh_27_V => ap_const_lv18_FFF,
        my_NN_tanh_28_V => ap_const_lv18_FFF,
        my_NN_tanh_29_V => ap_const_lv18_FFF,
        my_NN_tanh_30_V => ap_const_lv18_FFF,
        my_NN_tanh_31_V => ap_const_lv18_FFF,
        my_NN_tanh_32_V => ap_const_lv18_FFF,
        my_NN_tanh_33_V => ap_const_lv18_FFF,
        my_NN_tanh_34_V => ap_const_lv18_FFF,
        my_NN_tanh_35_V => ap_const_lv18_FFF,
        my_NN_tanh_36_V => ap_const_lv18_FFF,
        my_NN_tanh_37_V => ap_const_lv18_FFF,
        my_NN_tanh_38_V => ap_const_lv18_FFF,
        my_NN_tanh_39_V => ap_const_lv18_FFF,
        my_NN_tanh_40_V => ap_const_lv18_FFF,
        my_NN_tanh_41_V => ap_const_lv18_FFF,
        my_NN_tanh_42_V => ap_const_lv18_FFF,
        my_NN_tanh_43_V => ap_const_lv18_FFF,
        my_NN_tanh_44_V => ap_const_lv18_FFF,
        my_NN_tanh_45_V => ap_const_lv18_FFF,
        my_NN_tanh_46_V => ap_const_lv18_FFF,
        my_NN_tanh_47_V => ap_const_lv18_FFF,
        my_NN_tanh_48_V => ap_const_lv18_FFF,
        my_NN_tanh_49_V => ap_const_lv18_FFF,
        my_NN_tanh_50_V => ap_const_lv18_FFF,
        my_NN_tanh_51_V => ap_const_lv18_FFF,
        my_NN_tanh_52_V => ap_const_lv18_FFF,
        my_NN_tanh_53_V => ap_const_lv18_FFF,
        my_NN_tanh_54_V => ap_const_lv18_FFF,
        my_NN_tanh_55_V => ap_const_lv18_FFF,
        my_NN_tanh_56_V => ap_const_lv18_FFF,
        my_NN_tanh_57_V => ap_const_lv18_FFF,
        my_NN_tanh_58_V => ap_const_lv18_FFF,
        my_NN_tanh_59_V => ap_const_lv18_FFF,
        my_NN_tanh_60_V => ap_const_lv18_FFF,
        my_NN_tanh_61_V => ap_const_lv18_FFF,
        my_NN_tanh_62_V => ap_const_lv18_FFF,
        my_NN_tanh_63_V => ap_const_lv18_FFF,
        my_NN_tanh_64_V => ap_const_lv18_FFF,
        my_NN_tanh_65_V => ap_const_lv18_FFF,
        my_NN_tanh_66_V => ap_const_lv18_FFF,
        my_NN_tanh_67_V => ap_const_lv18_FFF,
        my_NN_tanh_68_V => ap_const_lv18_FFF,
        my_NN_tanh_69_V => ap_const_lv18_FFF,
        my_NN_tanh_70_V => ap_const_lv18_FFF,
        my_NN_tanh_71_V => ap_const_lv18_FFF,
        my_NN_tanh_72_V => ap_const_lv18_FFF,
        my_NN_tanh_73_V => ap_const_lv18_FFF,
        my_NN_tanh_74_V => ap_const_lv18_FFF,
        my_NN_tanh_75_V => ap_const_lv18_FFF,
        my_NN_tanh_76_V => ap_const_lv18_FFF,
        my_NN_tanh_77_V => ap_const_lv18_1000,
        my_NN_tanh_78_V => ap_const_lv18_1000,
        my_NN_tanh_79_V => ap_const_lv18_1000,
        my_NN_tanh_80_V => ap_const_lv18_1000,
        my_NN_tanh_81_V => ap_const_lv18_1000,
        my_NN_tanh_82_V => ap_const_lv18_1000,
        my_NN_tanh_83_V => ap_const_lv18_1000,
        my_NN_tanh_84_V => ap_const_lv18_1000,
        my_NN_tanh_85_V => ap_const_lv18_1000,
        my_NN_tanh_86_V => ap_const_lv18_1000,
        my_NN_tanh_87_V => ap_const_lv18_1000,
        my_NN_tanh_88_V => ap_const_lv18_1000,
        my_NN_tanh_89_V => ap_const_lv18_1000,
        my_NN_tanh_90_V => ap_const_lv18_1000,
        my_NN_tanh_91_V => ap_const_lv18_1000,
        my_NN_tanh_92_V => ap_const_lv18_1000,
        my_NN_tanh_93_V => ap_const_lv18_1000,
        my_NN_tanh_94_V => ap_const_lv18_1000,
        my_NN_tanh_95_V => ap_const_lv18_1000,
        my_NN_tanh_96_V => ap_const_lv18_1000,
        my_NN_tanh_97_V => ap_const_lv18_1000,
        my_NN_tanh_98_V => ap_const_lv18_1000,
        my_NN_tanh_99_V => ap_const_lv18_1000,
        my_NN_tanh_100_V => ap_const_lv18_1000,
        my_NN_tanh_101_V => ap_const_lv18_1000,
        my_NN_tanh_102_V => ap_const_lv18_1000,
        my_NN_tanh_103_V => ap_const_lv18_1000,
        my_NN_tanh_104_V => ap_const_lv18_1000,
        my_NN_tanh_105_V => ap_const_lv18_1000,
        my_NN_tanh_106_V => ap_const_lv18_1000,
        my_NN_tanh_107_V => ap_const_lv18_1000,
        my_NN_tanh_108_V => ap_const_lv18_1000,
        my_NN_tanh_109_V => ap_const_lv18_1000,
        my_NN_tanh_110_V => ap_const_lv18_1000,
        my_NN_tanh_111_V => ap_const_lv18_1000,
        my_NN_tanh_112_V => ap_const_lv18_1000,
        my_NN_tanh_113_V => ap_const_lv18_1000,
        my_NN_tanh_114_V => ap_const_lv18_1000,
        my_NN_tanh_115_V => ap_const_lv18_1000,
        my_NN_tanh_116_V => ap_const_lv18_1000,
        my_NN_tanh_117_V => ap_const_lv18_1000,
        my_NN_tanh_118_V => ap_const_lv18_1000,
        my_NN_tanh_119_V => ap_const_lv18_1000,
        my_NN_tanh_120_V => ap_const_lv18_1000,
        my_NN_tanh_121_V => ap_const_lv18_1000,
        my_NN_tanh_122_V => ap_const_lv18_1000,
        my_NN_tanh_123_V => ap_const_lv18_1000,
        my_NN_tanh_124_V => ap_const_lv18_1000,
        my_NN_tanh_125_V => ap_const_lv18_1000,
        my_NN_tanh_126_V => ap_const_lv18_1000,
        my_NN_tanh_127_V => ap_const_lv18_1000,
        my_NN_b_0_V => ap_const_lv18_D09,
        my_NN_b_1_V => ap_const_lv18_E7E,
        my_NN_b_2_V => ap_const_lv18_208,
        my_NN_b_3_V => ap_const_lv18_E9D,
        my_NN_b_4_V => ap_const_lv18_A1E,
        my_NN_b_5_V => ap_const_lv18_18F,
        my_NN_b_6_V => ap_const_lv18_474,
        my_NN_b_7_V => ap_const_lv18_8C0,
        my_NN_b_8_V => ap_const_lv18_F51,
        my_NN_b_9_V => ap_const_lv18_F70,
        my_NN_b_10_V => ap_const_lv18_285,
        my_NN_b_11_V => ap_const_lv18_F87,
        my_NN_w_0_V => ap_const_lv18_0,
        my_NN_w_1_V => ap_const_lv18_0,
        my_NN_w_2_V => ap_const_lv18_0,
        my_NN_w_3_V => ap_const_lv18_0,
        my_NN_w_4_V => ap_const_lv18_0,
        my_NN_w_5_V => ap_const_lv18_0,
        my_NN_w_6_V => ap_const_lv18_0,
        my_NN_w_7_V => ap_const_lv18_0,
        my_NN_w_8_V => ap_const_lv18_0,
        my_NN_w_9_V => ap_const_lv18_0,
        my_NN_w_10_V => ap_const_lv18_0,
        my_NN_w_11_V => ap_const_lv18_0,
        my_NN_w_12_V => ap_const_lv18_0,
        my_NN_w_13_V => ap_const_lv18_0,
        my_NN_w_14_V => ap_const_lv18_0,
        my_NN_w_15_V => ap_const_lv18_0,
        my_NN_w_16_V => ap_const_lv18_9925,
        my_NN_w_17_V => ap_const_lv18_4DA8,
        my_NN_w_18_V => ap_const_lv18_800B,
        my_NN_w_19_V => ap_const_lv18_16B3,
        my_NN_w_20_V => ap_const_lv18_437B,
        my_NN_w_21_V => ap_const_lv18_9284,
        my_NN_w_22_V => ap_const_lv18_7EC0,
        my_NN_w_23_V => ap_const_lv18_9984,
        my_NN_w_24_V => ap_const_lv18_68EB,
        my_NN_w_25_V => ap_const_lv18_5B6,
        my_NN_w_26_V => ap_const_lv18_87DC,
        my_NN_w_27_V => ap_const_lv18_9570,
        my_NN_w_28_V => ap_const_lv18_6C98,
        my_NN_w_29_V => ap_const_lv18_793D,
        my_NN_w_30_V => ap_const_lv18_76E6,
        my_NN_w_31_V => ap_const_lv18_3EC1,
        my_NN_w_32_V => ap_const_lv18_68E0,
        my_NN_w_33_V => ap_const_lv18_1B63,
        my_NN_w_34_V => ap_const_lv18_70F7,
        my_NN_w_35_V => ap_const_lv18_517,
        my_NN_w_36_V => ap_const_lv18_2C4E,
        my_NN_w_37_V => ap_const_lv18_763,
        my_NN_w_38_V => ap_const_lv18_F8A,
        my_NN_w_39_V => ap_const_lv18_83C0,
        my_NN_w_40_V => ap_const_lv18_6F2C,
        my_NN_w_41_V => ap_const_lv18_32BC,
        my_NN_w_42_V => ap_const_lv18_9809,
        my_NN_w_43_V => ap_const_lv18_582,
        my_NN_w_44_V => ap_const_lv18_4632,
        my_NN_w_45_V => ap_const_lv18_3D0C,
        my_NN_w_46_V => ap_const_lv18_7A7B,
        my_NN_w_47_V => ap_const_lv18_7F3B,
        my_NN_w_48_V => ap_const_lv18_1DE6,
        my_NN_w_49_V => ap_const_lv18_4E5C,
        my_NN_w_50_V => ap_const_lv18_474B,
        my_NN_w_51_V => ap_const_lv18_6768,
        my_NN_w_52_V => ap_const_lv18_717F,
        my_NN_w_53_V => ap_const_lv18_78BF,
        my_NN_w_54_V => ap_const_lv18_2C29,
        my_NN_w_55_V => ap_const_lv18_6CC0,
        my_NN_w_56_V => ap_const_lv18_68D0,
        my_NN_w_57_V => ap_const_lv18_1A04,
        my_NN_w_58_V => ap_const_lv18_130A,
        my_NN_w_59_V => ap_const_lv18_4FBC,
        my_NN_w_60_V => ap_const_lv18_998F,
        my_NN_w_61_V => ap_const_lv18_3676,
        my_NN_w_62_V => ap_const_lv18_5DA4,
        my_NN_w_63_V => ap_const_lv18_23CF,
        my_NN_n_V_i => my_NN_n_V,
        my_NN_n_V_o => StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o,
        my_NN_n_V_o_ap_vld => StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld);

    StgValue_237_my_NN_out_func_fu_2870 : component my_NN_out_func
    port map (
        Y0 => StgValue_237_my_NN_out_func_fu_2870_Y0,
        Y0_ap_vld => StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld,
        Y1 => StgValue_237_my_NN_out_func_fu_2870_Y1,
        Y1_ap_vld => StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld,
        x0 => x0,
        x1 => x1,
        x2 => x2,
        x3 => x3,
        my_NN_c_0_V => ap_const_lv18_3C19,
        my_NN_c_1_V => ap_const_lv18_4745,
        my_NN_c_2_V => ap_const_lv18_1468,
        my_NN_c_3_V => ap_const_lv18_4CBE,
        my_NN_c_4_V => ap_const_lv18_287A,
        my_NN_c_5_V => ap_const_lv18_2BC6,
        my_NN_c_6_V => ap_const_lv18_37ED,
        my_NN_c_7_V => ap_const_lv18_B17);





    my_NN_n_V_assign_proc : process(CLK)
    begin
        if (CLK'event and CLK =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                my_NN_n_V <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld)) then 
                my_NN_n_V <= StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o;
            end if; 
        end if;
    end process;


    x0_assign_proc : process(CLK)
    begin
        if (CLK'event and CLK =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                x0 <= ap_const_lv18_0;
            elsif ((ap_const_logic_1 = StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld)) then 
                x0 <= StgValue_231_my_NN_NN_func_fu_2420_x0_o;
            end if; 
        end if;
    end process;


    x1_assign_proc : process(CLK)
    begin
        if (CLK'event and CLK =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                x1 <= ap_const_lv18_0;
            elsif ((ap_const_logic_1 = StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld)) then 
                x1 <= StgValue_231_my_NN_NN_func_fu_2420_x1_o;
            end if; 
        end if;
    end process;


    x2_assign_proc : process(CLK)
    begin
        if (CLK'event and CLK =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                x2 <= ap_const_lv18_0;
            elsif ((ap_const_logic_1 = StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld)) then 
                x2 <= StgValue_231_my_NN_NN_func_fu_2420_x2_o;
            end if; 
        end if;
    end process;


    x3_assign_proc : process(CLK)
    begin
        if (CLK'event and CLK =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                x3 <= ap_const_lv18_0;
            elsif ((ap_const_logic_1 = StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld)) then 
                x3 <= StgValue_231_my_NN_NN_func_fu_2420_x3_o;
            end if; 
        end if;
    end process;

    Y0 <= StgValue_237_my_NN_out_func_fu_2870_Y0;
    Y1 <= StgValue_237_my_NN_out_func_fu_2870_Y1;
    ap_CS_fsm <= ap_const_lv4_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    my_NN_ssdm_thread_load_fu_3320_p1 <= ap_const_lv1_0;
end behav;
