// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "my_NN.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic my_NN::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> my_NN::ap_const_lv1_0 = "0";
const sc_lv<32> my_NN::ap_const_lv32_1 = "1";
const sc_lv<1> my_NN::ap_const_lv1_1 = "1";
const sc_lv<32> my_NN::ap_const_lv32_2 = "10";
const sc_lv<18> my_NN::ap_const_lv18_0 = "000000000000000000";
const sc_lv<32> my_NN::ap_const_lv32_3 = "11";
const sc_lv<3> my_NN::ap_const_lv3_0 = "000";
const sc_lv<18> my_NN::ap_const_lv18_3EB = "1111101011";
const sc_lv<18> my_NN::ap_const_lv18_764 = "11101100100";
const sc_lv<18> my_NN::ap_const_lv18_A29 = "101000101001";
const sc_lv<18> my_NN::ap_const_lv18_C2F = "110000101111";
const sc_lv<18> my_NN::ap_const_lv18_D92 = "110110010010";
const sc_lv<18> my_NN::ap_const_lv18_E7B = "111001111011";
const sc_lv<18> my_NN::ap_const_lv18_F0F = "111100001111";
const sc_lv<18> my_NN::ap_const_lv18_F6C = "111101101100";
const sc_lv<18> my_NN::ap_const_lv18_FA5 = "111110100101";
const sc_lv<18> my_NN::ap_const_lv18_FC9 = "111111001001";
const sc_lv<18> my_NN::ap_const_lv18_FDE = "111111011110";
const sc_lv<18> my_NN::ap_const_lv18_FEB = "111111101011";
const sc_lv<18> my_NN::ap_const_lv18_FF3 = "111111110011";
const sc_lv<18> my_NN::ap_const_lv18_FF8 = "111111111000";
const sc_lv<18> my_NN::ap_const_lv18_FFB = "111111111011";
const sc_lv<18> my_NN::ap_const_lv18_FFD = "111111111101";
const sc_lv<18> my_NN::ap_const_lv18_FFE = "111111111110";
const sc_lv<18> my_NN::ap_const_lv18_FFF = "111111111111";
const sc_lv<18> my_NN::ap_const_lv18_1000 = "1000000000000";
const sc_lv<18> my_NN::ap_const_lv18_9925 = "1001100100100101";
const sc_lv<18> my_NN::ap_const_lv18_4DA8 = "100110110101000";
const sc_lv<18> my_NN::ap_const_lv18_800B = "1000000000001011";
const sc_lv<18> my_NN::ap_const_lv18_16B3 = "1011010110011";
const sc_lv<18> my_NN::ap_const_lv18_437B = "100001101111011";
const sc_lv<18> my_NN::ap_const_lv18_9284 = "1001001010000100";
const sc_lv<18> my_NN::ap_const_lv18_7EC0 = "111111011000000";
const sc_lv<18> my_NN::ap_const_lv18_9984 = "1001100110000100";
const sc_lv<18> my_NN::ap_const_lv18_68EB = "110100011101011";
const sc_lv<18> my_NN::ap_const_lv18_5B6 = "10110110110";
const sc_lv<18> my_NN::ap_const_lv18_87DC = "1000011111011100";
const sc_lv<18> my_NN::ap_const_lv18_9570 = "1001010101110000";
const sc_lv<18> my_NN::ap_const_lv18_6C98 = "110110010011000";
const sc_lv<18> my_NN::ap_const_lv18_793D = "111100100111101";
const sc_lv<18> my_NN::ap_const_lv18_76E6 = "111011011100110";
const sc_lv<18> my_NN::ap_const_lv18_3EC1 = "11111011000001";
const sc_lv<18> my_NN::ap_const_lv18_68E0 = "110100011100000";
const sc_lv<18> my_NN::ap_const_lv18_1B63 = "1101101100011";
const sc_lv<18> my_NN::ap_const_lv18_70F7 = "111000011110111";
const sc_lv<18> my_NN::ap_const_lv18_517 = "10100010111";
const sc_lv<18> my_NN::ap_const_lv18_2C4E = "10110001001110";
const sc_lv<18> my_NN::ap_const_lv18_763 = "11101100011";
const sc_lv<18> my_NN::ap_const_lv18_F8A = "111110001010";
const sc_lv<18> my_NN::ap_const_lv18_83C0 = "1000001111000000";
const sc_lv<18> my_NN::ap_const_lv18_6F2C = "110111100101100";
const sc_lv<18> my_NN::ap_const_lv18_32BC = "11001010111100";
const sc_lv<18> my_NN::ap_const_lv18_9809 = "1001100000001001";
const sc_lv<18> my_NN::ap_const_lv18_582 = "10110000010";
const sc_lv<18> my_NN::ap_const_lv18_4632 = "100011000110010";
const sc_lv<18> my_NN::ap_const_lv18_3D0C = "11110100001100";
const sc_lv<18> my_NN::ap_const_lv18_7A7B = "111101001111011";
const sc_lv<18> my_NN::ap_const_lv18_7F3B = "111111100111011";
const sc_lv<18> my_NN::ap_const_lv18_1DE6 = "1110111100110";
const sc_lv<18> my_NN::ap_const_lv18_4E5C = "100111001011100";
const sc_lv<18> my_NN::ap_const_lv18_474B = "100011101001011";
const sc_lv<18> my_NN::ap_const_lv18_6768 = "110011101101000";
const sc_lv<18> my_NN::ap_const_lv18_717F = "111000101111111";
const sc_lv<18> my_NN::ap_const_lv18_78BF = "111100010111111";
const sc_lv<18> my_NN::ap_const_lv18_2C29 = "10110000101001";
const sc_lv<18> my_NN::ap_const_lv18_6CC0 = "110110011000000";
const sc_lv<18> my_NN::ap_const_lv18_68D0 = "110100011010000";
const sc_lv<18> my_NN::ap_const_lv18_1A04 = "1101000000100";
const sc_lv<18> my_NN::ap_const_lv18_130A = "1001100001010";
const sc_lv<18> my_NN::ap_const_lv18_4FBC = "100111110111100";
const sc_lv<18> my_NN::ap_const_lv18_998F = "1001100110001111";
const sc_lv<18> my_NN::ap_const_lv18_3676 = "11011001110110";
const sc_lv<18> my_NN::ap_const_lv18_5DA4 = "101110110100100";
const sc_lv<18> my_NN::ap_const_lv18_23CF = "10001111001111";
const sc_lv<18> my_NN::ap_const_lv18_D09 = "110100001001";
const sc_lv<18> my_NN::ap_const_lv18_E7E = "111001111110";
const sc_lv<18> my_NN::ap_const_lv18_208 = "1000001000";
const sc_lv<18> my_NN::ap_const_lv18_E9D = "111010011101";
const sc_lv<18> my_NN::ap_const_lv18_A1E = "101000011110";
const sc_lv<18> my_NN::ap_const_lv18_18F = "110001111";
const sc_lv<18> my_NN::ap_const_lv18_474 = "10001110100";
const sc_lv<18> my_NN::ap_const_lv18_8C0 = "100011000000";
const sc_lv<18> my_NN::ap_const_lv18_F51 = "111101010001";
const sc_lv<18> my_NN::ap_const_lv18_F70 = "111101110000";
const sc_lv<18> my_NN::ap_const_lv18_285 = "1010000101";
const sc_lv<18> my_NN::ap_const_lv18_F87 = "111110000111";
const sc_lv<18> my_NN::ap_const_lv18_3C19 = "11110000011001";
const sc_lv<18> my_NN::ap_const_lv18_4745 = "100011101000101";
const sc_lv<18> my_NN::ap_const_lv18_1468 = "1010001101000";
const sc_lv<18> my_NN::ap_const_lv18_4CBE = "100110010111110";
const sc_lv<18> my_NN::ap_const_lv18_287A = "10100001111010";
const sc_lv<18> my_NN::ap_const_lv18_2BC6 = "10101111000110";
const sc_lv<18> my_NN::ap_const_lv18_37ED = "11011111101101";
const sc_lv<18> my_NN::ap_const_lv18_B17 = "101100010111";
const sc_lv<4> my_NN::ap_const_lv4_0 = "0000";
const sc_logic my_NN::ap_const_logic_0 = sc_dt::Log_0;
const bool my_NN::ap_const_boolean_1 = true;

my_NN::my_NN(sc_module_name name) : sc_module(name), mVcdFile(0) {
    StgValue_231_my_NN_NN_func_fu_2420 = new my_NN_NN_func("StgValue_231_my_NN_NN_func_fu_2420");
    StgValue_231_my_NN_NN_func_fu_2420->ap_clk(CLK);
    StgValue_231_my_NN_NN_func_fu_2420->ap_rst(ap_rst);
    StgValue_231_my_NN_NN_func_fu_2420->U0(U0);
    StgValue_231_my_NN_NN_func_fu_2420->U1(U1);
    StgValue_231_my_NN_NN_func_fu_2420->U2(U2);
    StgValue_231_my_NN_NN_func_fu_2420->x0_i(x0);
    StgValue_231_my_NN_NN_func_fu_2420->x0_o(StgValue_231_my_NN_NN_func_fu_2420_x0_o);
    StgValue_231_my_NN_NN_func_fu_2420->x0_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld);
    StgValue_231_my_NN_NN_func_fu_2420->x1_i(x1);
    StgValue_231_my_NN_NN_func_fu_2420->x1_o(StgValue_231_my_NN_NN_func_fu_2420_x1_o);
    StgValue_231_my_NN_NN_func_fu_2420->x1_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld);
    StgValue_231_my_NN_NN_func_fu_2420->x2_i(x2);
    StgValue_231_my_NN_NN_func_fu_2420->x2_o(StgValue_231_my_NN_NN_func_fu_2420_x2_o);
    StgValue_231_my_NN_NN_func_fu_2420->x2_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld);
    StgValue_231_my_NN_NN_func_fu_2420->x3_i(x3);
    StgValue_231_my_NN_NN_func_fu_2420->x3_o(StgValue_231_my_NN_NN_func_fu_2420_x3_o);
    StgValue_231_my_NN_NN_func_fu_2420->x3_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_0_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_1_V(ap_var_for_const1);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_2_V(ap_var_for_const2);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_3_V(ap_var_for_const3);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_4_V(ap_var_for_const4);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_5_V(ap_var_for_const5);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_6_V(ap_var_for_const6);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_7_V(ap_var_for_const7);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_8_V(ap_var_for_const8);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_9_V(ap_var_for_const9);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_10_V(ap_var_for_const10);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_11_V(ap_var_for_const11);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_12_V(ap_var_for_const12);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_13_V(ap_var_for_const13);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_14_V(ap_var_for_const14);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_15_V(ap_var_for_const15);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_16_V(ap_var_for_const16);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_17_V(ap_var_for_const17);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_18_V(ap_var_for_const17);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_19_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_20_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_21_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_22_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_23_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_24_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_25_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_26_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_27_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_28_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_29_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_30_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_31_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_32_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_33_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_34_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_35_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_36_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_37_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_38_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_39_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_40_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_41_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_42_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_43_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_44_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_45_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_46_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_47_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_48_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_49_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_50_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_51_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_52_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_53_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_54_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_55_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_56_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_57_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_58_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_59_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_60_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_61_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_62_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_63_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_64_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_65_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_66_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_67_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_68_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_69_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_70_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_71_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_72_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_73_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_74_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_75_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_76_V(ap_var_for_const18);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_77_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_78_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_79_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_80_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_81_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_82_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_83_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_84_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_85_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_86_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_87_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_88_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_89_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_90_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_91_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_92_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_93_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_94_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_95_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_96_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_97_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_98_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_99_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_100_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_101_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_102_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_103_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_104_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_105_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_106_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_107_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_108_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_109_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_110_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_111_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_112_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_113_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_114_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_115_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_116_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_117_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_118_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_119_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_120_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_121_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_122_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_123_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_124_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_125_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_126_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_tanh_127_V(ap_var_for_const19);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_0_V(ap_var_for_const20);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_1_V(ap_var_for_const21);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_2_V(ap_var_for_const22);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_3_V(ap_var_for_const23);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_4_V(ap_var_for_const24);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_5_V(ap_var_for_const25);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_6_V(ap_var_for_const26);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_7_V(ap_var_for_const27);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_8_V(ap_var_for_const28);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_9_V(ap_var_for_const29);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_10_V(ap_var_for_const30);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_b_11_V(ap_var_for_const31);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_0_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_1_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_2_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_3_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_4_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_5_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_6_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_7_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_8_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_9_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_10_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_11_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_12_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_13_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_14_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_15_V(ap_var_for_const0);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_16_V(ap_var_for_const32);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_17_V(ap_var_for_const33);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_18_V(ap_var_for_const34);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_19_V(ap_var_for_const35);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_20_V(ap_var_for_const36);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_21_V(ap_var_for_const37);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_22_V(ap_var_for_const38);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_23_V(ap_var_for_const39);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_24_V(ap_var_for_const40);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_25_V(ap_var_for_const41);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_26_V(ap_var_for_const42);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_27_V(ap_var_for_const43);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_28_V(ap_var_for_const44);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_29_V(ap_var_for_const45);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_30_V(ap_var_for_const46);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_31_V(ap_var_for_const47);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_32_V(ap_var_for_const48);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_33_V(ap_var_for_const49);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_34_V(ap_var_for_const50);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_35_V(ap_var_for_const51);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_36_V(ap_var_for_const52);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_37_V(ap_var_for_const53);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_38_V(ap_var_for_const54);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_39_V(ap_var_for_const55);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_40_V(ap_var_for_const56);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_41_V(ap_var_for_const57);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_42_V(ap_var_for_const58);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_43_V(ap_var_for_const59);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_44_V(ap_var_for_const60);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_45_V(ap_var_for_const61);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_46_V(ap_var_for_const62);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_47_V(ap_var_for_const63);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_48_V(ap_var_for_const64);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_49_V(ap_var_for_const65);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_50_V(ap_var_for_const66);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_51_V(ap_var_for_const67);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_52_V(ap_var_for_const68);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_53_V(ap_var_for_const69);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_54_V(ap_var_for_const70);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_55_V(ap_var_for_const71);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_56_V(ap_var_for_const72);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_57_V(ap_var_for_const73);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_58_V(ap_var_for_const74);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_59_V(ap_var_for_const75);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_60_V(ap_var_for_const76);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_61_V(ap_var_for_const77);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_62_V(ap_var_for_const78);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_w_63_V(ap_var_for_const79);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_n_V_i(my_NN_n_V);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_n_V_o(StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o);
    StgValue_231_my_NN_NN_func_fu_2420->my_NN_n_V_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld);
    StgValue_237_my_NN_out_func_fu_2870 = new my_NN_out_func("StgValue_237_my_NN_out_func_fu_2870");
    StgValue_237_my_NN_out_func_fu_2870->Y0(StgValue_237_my_NN_out_func_fu_2870_Y0);
    StgValue_237_my_NN_out_func_fu_2870->Y0_ap_vld(StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld);
    StgValue_237_my_NN_out_func_fu_2870->Y1(StgValue_237_my_NN_out_func_fu_2870_Y1);
    StgValue_237_my_NN_out_func_fu_2870->Y1_ap_vld(StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld);
    StgValue_237_my_NN_out_func_fu_2870->x0(x0);
    StgValue_237_my_NN_out_func_fu_2870->x1(x1);
    StgValue_237_my_NN_out_func_fu_2870->x2(x2);
    StgValue_237_my_NN_out_func_fu_2870->x3(x3);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_0_V(ap_var_for_const80);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_1_V(ap_var_for_const81);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_2_V(ap_var_for_const82);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_3_V(ap_var_for_const83);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_4_V(ap_var_for_const84);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_5_V(ap_var_for_const85);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_6_V(ap_var_for_const86);
    StgValue_237_my_NN_out_func_fu_2870->my_NN_c_7_V(ap_var_for_const87);

    SC_METHOD(thread_my_NN_n_V);
    dont_initialize();
    sensitive << ( CLK.pos() );

    SC_METHOD(thread_x0);
    dont_initialize();
    sensitive << ( CLK.pos() );

    SC_METHOD(thread_x1);
    dont_initialize();
    sensitive << ( CLK.pos() );

    SC_METHOD(thread_x2);
    dont_initialize();
    sensitive << ( CLK.pos() );

    SC_METHOD(thread_x3);
    dont_initialize();
    sensitive << ( CLK.pos() );

    SC_METHOD(thread_Y0);
    sensitive << ( StgValue_237_my_NN_out_func_fu_2870_Y0 );
    sensitive << ( StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld );

    SC_METHOD(thread_Y1);
    sensitive << ( StgValue_237_my_NN_out_func_fu_2870_Y1 );
    sensitive << ( StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld );

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_my_NN_ssdm_thread_load_fu_3320_p1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( CLK.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const8);

    SC_THREAD(thread_ap_var_for_const9);

    SC_THREAD(thread_ap_var_for_const10);

    SC_THREAD(thread_ap_var_for_const11);

    SC_THREAD(thread_ap_var_for_const12);

    SC_THREAD(thread_ap_var_for_const13);

    SC_THREAD(thread_ap_var_for_const14);

    SC_THREAD(thread_ap_var_for_const15);

    SC_THREAD(thread_ap_var_for_const16);

    SC_THREAD(thread_ap_var_for_const17);

    SC_THREAD(thread_ap_var_for_const18);

    SC_THREAD(thread_ap_var_for_const19);

    SC_THREAD(thread_ap_var_for_const32);

    SC_THREAD(thread_ap_var_for_const33);

    SC_THREAD(thread_ap_var_for_const34);

    SC_THREAD(thread_ap_var_for_const35);

    SC_THREAD(thread_ap_var_for_const36);

    SC_THREAD(thread_ap_var_for_const37);

    SC_THREAD(thread_ap_var_for_const38);

    SC_THREAD(thread_ap_var_for_const39);

    SC_THREAD(thread_ap_var_for_const40);

    SC_THREAD(thread_ap_var_for_const41);

    SC_THREAD(thread_ap_var_for_const42);

    SC_THREAD(thread_ap_var_for_const43);

    SC_THREAD(thread_ap_var_for_const44);

    SC_THREAD(thread_ap_var_for_const45);

    SC_THREAD(thread_ap_var_for_const46);

    SC_THREAD(thread_ap_var_for_const47);

    SC_THREAD(thread_ap_var_for_const48);

    SC_THREAD(thread_ap_var_for_const49);

    SC_THREAD(thread_ap_var_for_const50);

    SC_THREAD(thread_ap_var_for_const51);

    SC_THREAD(thread_ap_var_for_const52);

    SC_THREAD(thread_ap_var_for_const53);

    SC_THREAD(thread_ap_var_for_const54);

    SC_THREAD(thread_ap_var_for_const55);

    SC_THREAD(thread_ap_var_for_const56);

    SC_THREAD(thread_ap_var_for_const57);

    SC_THREAD(thread_ap_var_for_const58);

    SC_THREAD(thread_ap_var_for_const59);

    SC_THREAD(thread_ap_var_for_const60);

    SC_THREAD(thread_ap_var_for_const61);

    SC_THREAD(thread_ap_var_for_const62);

    SC_THREAD(thread_ap_var_for_const63);

    SC_THREAD(thread_ap_var_for_const64);

    SC_THREAD(thread_ap_var_for_const65);

    SC_THREAD(thread_ap_var_for_const66);

    SC_THREAD(thread_ap_var_for_const67);

    SC_THREAD(thread_ap_var_for_const68);

    SC_THREAD(thread_ap_var_for_const69);

    SC_THREAD(thread_ap_var_for_const70);

    SC_THREAD(thread_ap_var_for_const71);

    SC_THREAD(thread_ap_var_for_const72);

    SC_THREAD(thread_ap_var_for_const73);

    SC_THREAD(thread_ap_var_for_const74);

    SC_THREAD(thread_ap_var_for_const75);

    SC_THREAD(thread_ap_var_for_const76);

    SC_THREAD(thread_ap_var_for_const77);

    SC_THREAD(thread_ap_var_for_const78);

    SC_THREAD(thread_ap_var_for_const79);

    SC_THREAD(thread_ap_var_for_const20);

    SC_THREAD(thread_ap_var_for_const21);

    SC_THREAD(thread_ap_var_for_const22);

    SC_THREAD(thread_ap_var_for_const23);

    SC_THREAD(thread_ap_var_for_const24);

    SC_THREAD(thread_ap_var_for_const25);

    SC_THREAD(thread_ap_var_for_const26);

    SC_THREAD(thread_ap_var_for_const27);

    SC_THREAD(thread_ap_var_for_const28);

    SC_THREAD(thread_ap_var_for_const29);

    SC_THREAD(thread_ap_var_for_const30);

    SC_THREAD(thread_ap_var_for_const31);

    SC_THREAD(thread_ap_var_for_const80);

    SC_THREAD(thread_ap_var_for_const81);

    SC_THREAD(thread_ap_var_for_const82);

    SC_THREAD(thread_ap_var_for_const83);

    SC_THREAD(thread_ap_var_for_const84);

    SC_THREAD(thread_ap_var_for_const85);

    SC_THREAD(thread_ap_var_for_const86);

    SC_THREAD(thread_ap_var_for_const87);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "my_NN_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, U0, "(port)U0");
    sc_trace(mVcdFile, U1, "(port)U1");
    sc_trace(mVcdFile, U2, "(port)U2");
    sc_trace(mVcdFile, CLK, "(port)CLK");
    sc_trace(mVcdFile, Y0, "(port)Y0");
    sc_trace(mVcdFile, Y1, "(port)Y1");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, my_NN_ssdm_thread_load_fu_3320_p1, "my_NN_ssdm_thread_load_fu_3320_p1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x0_o, "StgValue_231_my_NN_NN_func_fu_2420_x0_o");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld, "StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x1_o, "StgValue_231_my_NN_NN_func_fu_2420_x1_o");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld, "StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x2_o, "StgValue_231_my_NN_NN_func_fu_2420_x2_o");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld, "StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x3_o, "StgValue_231_my_NN_NN_func_fu_2420_x3_o");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld, "StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o, "StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o");
    sc_trace(mVcdFile, StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld, "StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld");
    sc_trace(mVcdFile, StgValue_237_my_NN_out_func_fu_2870_Y0, "StgValue_237_my_NN_out_func_fu_2870_Y0");
    sc_trace(mVcdFile, StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld, "StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld");
    sc_trace(mVcdFile, StgValue_237_my_NN_out_func_fu_2870_Y1, "StgValue_237_my_NN_out_func_fu_2870_Y1");
    sc_trace(mVcdFile, StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld, "StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, x0, "x0");
    sc_trace(mVcdFile, x1, "x1");
    sc_trace(mVcdFile, x2, "x2");
    sc_trace(mVcdFile, x3, "x3");
    sc_trace(mVcdFile, my_NN_n_V, "my_NN_n_V");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
#endif

    }
    mHdltvinHandle.open("my_NN.hdltvin.dat");
    mHdltvoutHandle.open("my_NN.hdltvout.dat");
}

my_NN::~my_NN() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete StgValue_231_my_NN_NN_func_fu_2420;
    delete StgValue_237_my_NN_out_func_fu_2870;
}

void my_NN::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv18_0;
}

void my_NN::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv18_3EB;
}

void my_NN::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv18_764;
}

void my_NN::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv18_A29;
}

void my_NN::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv18_C2F;
}

void my_NN::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv18_D92;
}

void my_NN::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_lv18_E7B;
}

void my_NN::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv18_F0F;
}

void my_NN::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv18_F6C;
}

void my_NN::thread_ap_var_for_const9() {
    ap_var_for_const9 = ap_const_lv18_FA5;
}

void my_NN::thread_ap_var_for_const10() {
    ap_var_for_const10 = ap_const_lv18_FC9;
}

void my_NN::thread_ap_var_for_const11() {
    ap_var_for_const11 = ap_const_lv18_FDE;
}

void my_NN::thread_ap_var_for_const12() {
    ap_var_for_const12 = ap_const_lv18_FEB;
}

void my_NN::thread_ap_var_for_const13() {
    ap_var_for_const13 = ap_const_lv18_FF3;
}

void my_NN::thread_ap_var_for_const14() {
    ap_var_for_const14 = ap_const_lv18_FF8;
}

void my_NN::thread_ap_var_for_const15() {
    ap_var_for_const15 = ap_const_lv18_FFB;
}

void my_NN::thread_ap_var_for_const16() {
    ap_var_for_const16 = ap_const_lv18_FFD;
}

void my_NN::thread_ap_var_for_const17() {
    ap_var_for_const17 = ap_const_lv18_FFE;
}

void my_NN::thread_ap_var_for_const18() {
    ap_var_for_const18 = ap_const_lv18_FFF;
}

void my_NN::thread_ap_var_for_const19() {
    ap_var_for_const19 = ap_const_lv18_1000;
}

void my_NN::thread_ap_var_for_const32() {
    ap_var_for_const32 = ap_const_lv18_9925;
}

void my_NN::thread_ap_var_for_const33() {
    ap_var_for_const33 = ap_const_lv18_4DA8;
}

void my_NN::thread_ap_var_for_const34() {
    ap_var_for_const34 = ap_const_lv18_800B;
}

void my_NN::thread_ap_var_for_const35() {
    ap_var_for_const35 = ap_const_lv18_16B3;
}

void my_NN::thread_ap_var_for_const36() {
    ap_var_for_const36 = ap_const_lv18_437B;
}

void my_NN::thread_ap_var_for_const37() {
    ap_var_for_const37 = ap_const_lv18_9284;
}

void my_NN::thread_ap_var_for_const38() {
    ap_var_for_const38 = ap_const_lv18_7EC0;
}

void my_NN::thread_ap_var_for_const39() {
    ap_var_for_const39 = ap_const_lv18_9984;
}

void my_NN::thread_ap_var_for_const40() {
    ap_var_for_const40 = ap_const_lv18_68EB;
}

void my_NN::thread_ap_var_for_const41() {
    ap_var_for_const41 = ap_const_lv18_5B6;
}

void my_NN::thread_ap_var_for_const42() {
    ap_var_for_const42 = ap_const_lv18_87DC;
}

void my_NN::thread_ap_var_for_const43() {
    ap_var_for_const43 = ap_const_lv18_9570;
}

void my_NN::thread_ap_var_for_const44() {
    ap_var_for_const44 = ap_const_lv18_6C98;
}

void my_NN::thread_ap_var_for_const45() {
    ap_var_for_const45 = ap_const_lv18_793D;
}

void my_NN::thread_ap_var_for_const46() {
    ap_var_for_const46 = ap_const_lv18_76E6;
}

void my_NN::thread_ap_var_for_const47() {
    ap_var_for_const47 = ap_const_lv18_3EC1;
}

void my_NN::thread_ap_var_for_const48() {
    ap_var_for_const48 = ap_const_lv18_68E0;
}

void my_NN::thread_ap_var_for_const49() {
    ap_var_for_const49 = ap_const_lv18_1B63;
}

void my_NN::thread_ap_var_for_const50() {
    ap_var_for_const50 = ap_const_lv18_70F7;
}

void my_NN::thread_ap_var_for_const51() {
    ap_var_for_const51 = ap_const_lv18_517;
}

void my_NN::thread_ap_var_for_const52() {
    ap_var_for_const52 = ap_const_lv18_2C4E;
}

void my_NN::thread_ap_var_for_const53() {
    ap_var_for_const53 = ap_const_lv18_763;
}

void my_NN::thread_ap_var_for_const54() {
    ap_var_for_const54 = ap_const_lv18_F8A;
}

void my_NN::thread_ap_var_for_const55() {
    ap_var_for_const55 = ap_const_lv18_83C0;
}

void my_NN::thread_ap_var_for_const56() {
    ap_var_for_const56 = ap_const_lv18_6F2C;
}

void my_NN::thread_ap_var_for_const57() {
    ap_var_for_const57 = ap_const_lv18_32BC;
}

void my_NN::thread_ap_var_for_const58() {
    ap_var_for_const58 = ap_const_lv18_9809;
}

void my_NN::thread_ap_var_for_const59() {
    ap_var_for_const59 = ap_const_lv18_582;
}

void my_NN::thread_ap_var_for_const60() {
    ap_var_for_const60 = ap_const_lv18_4632;
}

void my_NN::thread_ap_var_for_const61() {
    ap_var_for_const61 = ap_const_lv18_3D0C;
}

void my_NN::thread_ap_var_for_const62() {
    ap_var_for_const62 = ap_const_lv18_7A7B;
}

void my_NN::thread_ap_var_for_const63() {
    ap_var_for_const63 = ap_const_lv18_7F3B;
}

void my_NN::thread_ap_var_for_const64() {
    ap_var_for_const64 = ap_const_lv18_1DE6;
}

void my_NN::thread_ap_var_for_const65() {
    ap_var_for_const65 = ap_const_lv18_4E5C;
}

void my_NN::thread_ap_var_for_const66() {
    ap_var_for_const66 = ap_const_lv18_474B;
}

void my_NN::thread_ap_var_for_const67() {
    ap_var_for_const67 = ap_const_lv18_6768;
}

void my_NN::thread_ap_var_for_const68() {
    ap_var_for_const68 = ap_const_lv18_717F;
}

void my_NN::thread_ap_var_for_const69() {
    ap_var_for_const69 = ap_const_lv18_78BF;
}

void my_NN::thread_ap_var_for_const70() {
    ap_var_for_const70 = ap_const_lv18_2C29;
}

void my_NN::thread_ap_var_for_const71() {
    ap_var_for_const71 = ap_const_lv18_6CC0;
}

void my_NN::thread_ap_var_for_const72() {
    ap_var_for_const72 = ap_const_lv18_68D0;
}

void my_NN::thread_ap_var_for_const73() {
    ap_var_for_const73 = ap_const_lv18_1A04;
}

void my_NN::thread_ap_var_for_const74() {
    ap_var_for_const74 = ap_const_lv18_130A;
}

void my_NN::thread_ap_var_for_const75() {
    ap_var_for_const75 = ap_const_lv18_4FBC;
}

void my_NN::thread_ap_var_for_const76() {
    ap_var_for_const76 = ap_const_lv18_998F;
}

void my_NN::thread_ap_var_for_const77() {
    ap_var_for_const77 = ap_const_lv18_3676;
}

void my_NN::thread_ap_var_for_const78() {
    ap_var_for_const78 = ap_const_lv18_5DA4;
}

void my_NN::thread_ap_var_for_const79() {
    ap_var_for_const79 = ap_const_lv18_23CF;
}

void my_NN::thread_ap_var_for_const20() {
    ap_var_for_const20 = ap_const_lv18_D09;
}

void my_NN::thread_ap_var_for_const21() {
    ap_var_for_const21 = ap_const_lv18_E7E;
}

void my_NN::thread_ap_var_for_const22() {
    ap_var_for_const22 = ap_const_lv18_208;
}

void my_NN::thread_ap_var_for_const23() {
    ap_var_for_const23 = ap_const_lv18_E9D;
}

void my_NN::thread_ap_var_for_const24() {
    ap_var_for_const24 = ap_const_lv18_A1E;
}

void my_NN::thread_ap_var_for_const25() {
    ap_var_for_const25 = ap_const_lv18_18F;
}

void my_NN::thread_ap_var_for_const26() {
    ap_var_for_const26 = ap_const_lv18_474;
}

void my_NN::thread_ap_var_for_const27() {
    ap_var_for_const27 = ap_const_lv18_8C0;
}

void my_NN::thread_ap_var_for_const28() {
    ap_var_for_const28 = ap_const_lv18_F51;
}

void my_NN::thread_ap_var_for_const29() {
    ap_var_for_const29 = ap_const_lv18_F70;
}

void my_NN::thread_ap_var_for_const30() {
    ap_var_for_const30 = ap_const_lv18_285;
}

void my_NN::thread_ap_var_for_const31() {
    ap_var_for_const31 = ap_const_lv18_F87;
}

void my_NN::thread_ap_var_for_const80() {
    ap_var_for_const80 = ap_const_lv18_3C19;
}

void my_NN::thread_ap_var_for_const81() {
    ap_var_for_const81 = ap_const_lv18_4745;
}

void my_NN::thread_ap_var_for_const82() {
    ap_var_for_const82 = ap_const_lv18_1468;
}

void my_NN::thread_ap_var_for_const83() {
    ap_var_for_const83 = ap_const_lv18_4CBE;
}

void my_NN::thread_ap_var_for_const84() {
    ap_var_for_const84 = ap_const_lv18_287A;
}

void my_NN::thread_ap_var_for_const85() {
    ap_var_for_const85 = ap_const_lv18_2BC6;
}

void my_NN::thread_ap_var_for_const86() {
    ap_var_for_const86 = ap_const_lv18_37ED;
}

void my_NN::thread_ap_var_for_const87() {
    ap_var_for_const87 = ap_const_lv18_B17;
}

void my_NN::thread_my_NN_n_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        my_NN_n_V = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld.read())) {
        my_NN_n_V = StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o.read();
    }
}

void my_NN::thread_x0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x0 = ap_const_lv18_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld.read())) {
        x0 = StgValue_231_my_NN_NN_func_fu_2420_x0_o.read();
    }
}

void my_NN::thread_x1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x1 = ap_const_lv18_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld.read())) {
        x1 = StgValue_231_my_NN_NN_func_fu_2420_x1_o.read();
    }
}

void my_NN::thread_x2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x2 = ap_const_lv18_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld.read())) {
        x2 = StgValue_231_my_NN_NN_func_fu_2420_x2_o.read();
    }
}

void my_NN::thread_x3() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x3 = ap_const_lv18_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld.read())) {
        x3 = StgValue_231_my_NN_NN_func_fu_2420_x3_o.read();
    }
}

void my_NN::thread_Y0() {
    Y0 = StgValue_237_my_NN_out_func_fu_2870_Y0.read();
}

void my_NN::thread_Y1() {
    Y1 = StgValue_237_my_NN_out_func_fu_2870_Y1.read();
}

void my_NN::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_const_lv4_0;
}

void my_NN::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void my_NN::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void my_NN::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void my_NN::thread_my_NN_ssdm_thread_load_fu_3320_p1() {
    my_NN_ssdm_thread_load_fu_3320_p1 = ap_const_lv1_0;
}

void my_NN::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"U0\" :  \"" << U0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"U1\" :  \"" << U1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"U2\" :  \"" << U2.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"Y0\" :  \"" << Y0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Y1\" :  \"" << Y1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

