// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "my_NN_out_func.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool my_NN_out_func::ap_const_boolean_1 = true;
const sc_logic my_NN_out_func::ap_const_logic_0 = sc_dt::Log_0;
const sc_logic my_NN_out_func::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<32> my_NN_out_func::ap_const_lv32_C = "1100";
const sc_lv<32> my_NN_out_func::ap_const_lv32_1D = "11101";

my_NN_out_func::my_NN_out_func(sc_module_name name) : sc_module(name), mVcdFile(0) {
    my_NN_mac_muladd_fYi_U263 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U263");
    my_NN_mac_muladd_fYi_U263->din0(x0);
    my_NN_mac_muladd_fYi_U263->din1(my_NN_c_0_V);
    my_NN_mac_muladd_fYi_U263->din2(p_Val2_1_fu_673_p2);
    my_NN_mac_muladd_fYi_U263->dout(grp_fu_666_p3);
    my_NN_mul_mul_18sg8j_U264 = new my_NN_mul_mul_18sg8j<1,1,18,18,30>("my_NN_mul_mul_18sg8j_U264");
    my_NN_mul_mul_18sg8j_U264->din0(x1);
    my_NN_mul_mul_18sg8j_U264->din1(my_NN_c_2_V);
    my_NN_mul_mul_18sg8j_U264->dout(p_Val2_1_fu_673_p2);
    my_NN_mac_muladd_fYi_U265 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U265");
    my_NN_mac_muladd_fYi_U265->din0(x2);
    my_NN_mac_muladd_fYi_U265->din1(my_NN_c_4_V);
    my_NN_mac_muladd_fYi_U265->din2(grp_fu_666_p3);
    my_NN_mac_muladd_fYi_U265->dout(grp_fu_680_p3);
    my_NN_mac_muladd_fYi_U266 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U266");
    my_NN_mac_muladd_fYi_U266->din0(x3);
    my_NN_mac_muladd_fYi_U266->din1(my_NN_c_6_V);
    my_NN_mac_muladd_fYi_U266->din2(grp_fu_680_p3);
    my_NN_mac_muladd_fYi_U266->dout(grp_fu_688_p3);
    my_NN_mac_muladd_fYi_U267 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U267");
    my_NN_mac_muladd_fYi_U267->din0(x0);
    my_NN_mac_muladd_fYi_U267->din1(my_NN_c_1_V);
    my_NN_mac_muladd_fYi_U267->din2(p_Val2_8_fu_704_p2);
    my_NN_mac_muladd_fYi_U267->dout(grp_fu_697_p3);
    my_NN_mul_mul_18sg8j_U268 = new my_NN_mul_mul_18sg8j<1,1,18,18,30>("my_NN_mul_mul_18sg8j_U268");
    my_NN_mul_mul_18sg8j_U268->din0(x1);
    my_NN_mul_mul_18sg8j_U268->din1(my_NN_c_3_V);
    my_NN_mul_mul_18sg8j_U268->dout(p_Val2_8_fu_704_p2);
    my_NN_mac_muladd_fYi_U269 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U269");
    my_NN_mac_muladd_fYi_U269->din0(x2);
    my_NN_mac_muladd_fYi_U269->din1(my_NN_c_5_V);
    my_NN_mac_muladd_fYi_U269->din2(grp_fu_697_p3);
    my_NN_mac_muladd_fYi_U269->dout(grp_fu_711_p3);
    my_NN_mac_muladd_fYi_U270 = new my_NN_mac_muladd_fYi<1,1,18,18,30,30>("my_NN_mac_muladd_fYi_U270");
    my_NN_mac_muladd_fYi_U270->din0(x3);
    my_NN_mac_muladd_fYi_U270->din1(my_NN_c_7_V);
    my_NN_mac_muladd_fYi_U270->din2(grp_fu_711_p3);
    my_NN_mac_muladd_fYi_U270->dout(grp_fu_719_p3);

    SC_METHOD(thread_Y0);
    sensitive << ( grp_fu_688_p3 );

    SC_METHOD(thread_Y0_ap_vld);

    SC_METHOD(thread_Y1);
    sensitive << ( grp_fu_719_p3 );

    SC_METHOD(thread_Y1_ap_vld);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "my_NN_out_func_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, Y0, "(port)Y0");
    sc_trace(mVcdFile, Y0_ap_vld, "(port)Y0_ap_vld");
    sc_trace(mVcdFile, Y1, "(port)Y1");
    sc_trace(mVcdFile, Y1_ap_vld, "(port)Y1_ap_vld");
    sc_trace(mVcdFile, x0, "(port)x0");
    sc_trace(mVcdFile, x1, "(port)x1");
    sc_trace(mVcdFile, x2, "(port)x2");
    sc_trace(mVcdFile, x3, "(port)x3");
    sc_trace(mVcdFile, my_NN_c_0_V, "(port)my_NN_c_0_V");
    sc_trace(mVcdFile, my_NN_c_1_V, "(port)my_NN_c_1_V");
    sc_trace(mVcdFile, my_NN_c_2_V, "(port)my_NN_c_2_V");
    sc_trace(mVcdFile, my_NN_c_3_V, "(port)my_NN_c_3_V");
    sc_trace(mVcdFile, my_NN_c_4_V, "(port)my_NN_c_4_V");
    sc_trace(mVcdFile, my_NN_c_5_V, "(port)my_NN_c_5_V");
    sc_trace(mVcdFile, my_NN_c_6_V, "(port)my_NN_c_6_V");
    sc_trace(mVcdFile, my_NN_c_7_V, "(port)my_NN_c_7_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_fu_688_p3, "grp_fu_688_p3");
    sc_trace(mVcdFile, grp_fu_719_p3, "grp_fu_719_p3");
    sc_trace(mVcdFile, p_Val2_1_fu_673_p2, "p_Val2_1_fu_673_p2");
    sc_trace(mVcdFile, grp_fu_666_p3, "grp_fu_666_p3");
    sc_trace(mVcdFile, grp_fu_680_p3, "grp_fu_680_p3");
    sc_trace(mVcdFile, p_Val2_8_fu_704_p2, "p_Val2_8_fu_704_p2");
    sc_trace(mVcdFile, grp_fu_697_p3, "grp_fu_697_p3");
    sc_trace(mVcdFile, grp_fu_711_p3, "grp_fu_711_p3");
#endif

    }
}

my_NN_out_func::~my_NN_out_func() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete my_NN_mac_muladd_fYi_U263;
    delete my_NN_mul_mul_18sg8j_U264;
    delete my_NN_mac_muladd_fYi_U265;
    delete my_NN_mac_muladd_fYi_U266;
    delete my_NN_mac_muladd_fYi_U267;
    delete my_NN_mul_mul_18sg8j_U268;
    delete my_NN_mac_muladd_fYi_U269;
    delete my_NN_mac_muladd_fYi_U270;
}

void my_NN_out_func::thread_Y0() {
    Y0 = grp_fu_688_p3.read().range(29, 12);
}

void my_NN_out_func::thread_Y0_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        Y0_ap_vld = ap_const_logic_1;
    } else {
        Y0_ap_vld = ap_const_logic_0;
    }
}

void my_NN_out_func::thread_Y1() {
    Y1 = grp_fu_719_p3.read().range(29, 12);
}

void my_NN_out_func::thread_Y1_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        Y1_ap_vld = ap_const_logic_1;
    } else {
        Y1_ap_vld = ap_const_logic_0;
    }
}

}

