// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_NN,hls_ip_2018_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z100ffg1156-1,HLS_INPUT_CLOCK=200.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=29.931000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=48,HLS_SYN_FF=75,HLS_SYN_LUT=4025}" *)

module my_NN (
        U0,
        U1,
        U2,
        CLK,
        Y0,
        Y1,
        ap_rst
);


input  [17:0] U0;
input  [17:0] U1;
input  [17:0] U2;
input   CLK;
output  [17:0] Y0;
output  [17:0] Y1;
input   ap_rst;

wire   [0:0] my_NN_ssdm_thread_load_fu_3320_p1;
wire   [3:0] ap_CS_fsm;
wire   [17:0] StgValue_231_my_NN_NN_func_fu_2420_x0_o;
wire    StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld;
wire   [17:0] StgValue_231_my_NN_NN_func_fu_2420_x1_o;
wire    StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld;
wire   [17:0] StgValue_231_my_NN_NN_func_fu_2420_x2_o;
wire    StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld;
wire   [17:0] StgValue_231_my_NN_NN_func_fu_2420_x3_o;
wire    StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld;
wire   [2:0] StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o;
wire    StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld;
wire   [17:0] StgValue_237_my_NN_out_func_fu_2870_Y0;
wire    StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld;
wire   [17:0] StgValue_237_my_NN_out_func_fu_2870_Y1;
wire    StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld;
wire    ap_CS_fsm_state2;
reg   [17:0] x0;
reg   [17:0] x1;
reg   [17:0] x2;
reg   [17:0] x3;
reg   [2:0] my_NN_n_V;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;

my_NN_NN_func StgValue_231_my_NN_NN_func_fu_2420(
    .ap_clk(CLK),
    .ap_rst(ap_rst),
    .U0(U0),
    .U1(U1),
    .U2(U2),
    .x0_i(x0),
    .x0_o(StgValue_231_my_NN_NN_func_fu_2420_x0_o),
    .x0_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld),
    .x1_i(x1),
    .x1_o(StgValue_231_my_NN_NN_func_fu_2420_x1_o),
    .x1_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld),
    .x2_i(x2),
    .x2_o(StgValue_231_my_NN_NN_func_fu_2420_x2_o),
    .x2_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld),
    .x3_i(x3),
    .x3_o(StgValue_231_my_NN_NN_func_fu_2420_x3_o),
    .x3_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld),
    .my_NN_tanh_0_V(18'd0),
    .my_NN_tanh_1_V(18'd1003),
    .my_NN_tanh_2_V(18'd1892),
    .my_NN_tanh_3_V(18'd2601),
    .my_NN_tanh_4_V(18'd3119),
    .my_NN_tanh_5_V(18'd3474),
    .my_NN_tanh_6_V(18'd3707),
    .my_NN_tanh_7_V(18'd3855),
    .my_NN_tanh_8_V(18'd3948),
    .my_NN_tanh_9_V(18'd4005),
    .my_NN_tanh_10_V(18'd4041),
    .my_NN_tanh_11_V(18'd4062),
    .my_NN_tanh_12_V(18'd4075),
    .my_NN_tanh_13_V(18'd4083),
    .my_NN_tanh_14_V(18'd4088),
    .my_NN_tanh_15_V(18'd4091),
    .my_NN_tanh_16_V(18'd4093),
    .my_NN_tanh_17_V(18'd4094),
    .my_NN_tanh_18_V(18'd4094),
    .my_NN_tanh_19_V(18'd4095),
    .my_NN_tanh_20_V(18'd4095),
    .my_NN_tanh_21_V(18'd4095),
    .my_NN_tanh_22_V(18'd4095),
    .my_NN_tanh_23_V(18'd4095),
    .my_NN_tanh_24_V(18'd4095),
    .my_NN_tanh_25_V(18'd4095),
    .my_NN_tanh_26_V(18'd4095),
    .my_NN_tanh_27_V(18'd4095),
    .my_NN_tanh_28_V(18'd4095),
    .my_NN_tanh_29_V(18'd4095),
    .my_NN_tanh_30_V(18'd4095),
    .my_NN_tanh_31_V(18'd4095),
    .my_NN_tanh_32_V(18'd4095),
    .my_NN_tanh_33_V(18'd4095),
    .my_NN_tanh_34_V(18'd4095),
    .my_NN_tanh_35_V(18'd4095),
    .my_NN_tanh_36_V(18'd4095),
    .my_NN_tanh_37_V(18'd4095),
    .my_NN_tanh_38_V(18'd4095),
    .my_NN_tanh_39_V(18'd4095),
    .my_NN_tanh_40_V(18'd4095),
    .my_NN_tanh_41_V(18'd4095),
    .my_NN_tanh_42_V(18'd4095),
    .my_NN_tanh_43_V(18'd4095),
    .my_NN_tanh_44_V(18'd4095),
    .my_NN_tanh_45_V(18'd4095),
    .my_NN_tanh_46_V(18'd4095),
    .my_NN_tanh_47_V(18'd4095),
    .my_NN_tanh_48_V(18'd4095),
    .my_NN_tanh_49_V(18'd4095),
    .my_NN_tanh_50_V(18'd4095),
    .my_NN_tanh_51_V(18'd4095),
    .my_NN_tanh_52_V(18'd4095),
    .my_NN_tanh_53_V(18'd4095),
    .my_NN_tanh_54_V(18'd4095),
    .my_NN_tanh_55_V(18'd4095),
    .my_NN_tanh_56_V(18'd4095),
    .my_NN_tanh_57_V(18'd4095),
    .my_NN_tanh_58_V(18'd4095),
    .my_NN_tanh_59_V(18'd4095),
    .my_NN_tanh_60_V(18'd4095),
    .my_NN_tanh_61_V(18'd4095),
    .my_NN_tanh_62_V(18'd4095),
    .my_NN_tanh_63_V(18'd4095),
    .my_NN_tanh_64_V(18'd4095),
    .my_NN_tanh_65_V(18'd4095),
    .my_NN_tanh_66_V(18'd4095),
    .my_NN_tanh_67_V(18'd4095),
    .my_NN_tanh_68_V(18'd4095),
    .my_NN_tanh_69_V(18'd4095),
    .my_NN_tanh_70_V(18'd4095),
    .my_NN_tanh_71_V(18'd4095),
    .my_NN_tanh_72_V(18'd4095),
    .my_NN_tanh_73_V(18'd4095),
    .my_NN_tanh_74_V(18'd4095),
    .my_NN_tanh_75_V(18'd4095),
    .my_NN_tanh_76_V(18'd4095),
    .my_NN_tanh_77_V(18'd4096),
    .my_NN_tanh_78_V(18'd4096),
    .my_NN_tanh_79_V(18'd4096),
    .my_NN_tanh_80_V(18'd4096),
    .my_NN_tanh_81_V(18'd4096),
    .my_NN_tanh_82_V(18'd4096),
    .my_NN_tanh_83_V(18'd4096),
    .my_NN_tanh_84_V(18'd4096),
    .my_NN_tanh_85_V(18'd4096),
    .my_NN_tanh_86_V(18'd4096),
    .my_NN_tanh_87_V(18'd4096),
    .my_NN_tanh_88_V(18'd4096),
    .my_NN_tanh_89_V(18'd4096),
    .my_NN_tanh_90_V(18'd4096),
    .my_NN_tanh_91_V(18'd4096),
    .my_NN_tanh_92_V(18'd4096),
    .my_NN_tanh_93_V(18'd4096),
    .my_NN_tanh_94_V(18'd4096),
    .my_NN_tanh_95_V(18'd4096),
    .my_NN_tanh_96_V(18'd4096),
    .my_NN_tanh_97_V(18'd4096),
    .my_NN_tanh_98_V(18'd4096),
    .my_NN_tanh_99_V(18'd4096),
    .my_NN_tanh_100_V(18'd4096),
    .my_NN_tanh_101_V(18'd4096),
    .my_NN_tanh_102_V(18'd4096),
    .my_NN_tanh_103_V(18'd4096),
    .my_NN_tanh_104_V(18'd4096),
    .my_NN_tanh_105_V(18'd4096),
    .my_NN_tanh_106_V(18'd4096),
    .my_NN_tanh_107_V(18'd4096),
    .my_NN_tanh_108_V(18'd4096),
    .my_NN_tanh_109_V(18'd4096),
    .my_NN_tanh_110_V(18'd4096),
    .my_NN_tanh_111_V(18'd4096),
    .my_NN_tanh_112_V(18'd4096),
    .my_NN_tanh_113_V(18'd4096),
    .my_NN_tanh_114_V(18'd4096),
    .my_NN_tanh_115_V(18'd4096),
    .my_NN_tanh_116_V(18'd4096),
    .my_NN_tanh_117_V(18'd4096),
    .my_NN_tanh_118_V(18'd4096),
    .my_NN_tanh_119_V(18'd4096),
    .my_NN_tanh_120_V(18'd4096),
    .my_NN_tanh_121_V(18'd4096),
    .my_NN_tanh_122_V(18'd4096),
    .my_NN_tanh_123_V(18'd4096),
    .my_NN_tanh_124_V(18'd4096),
    .my_NN_tanh_125_V(18'd4096),
    .my_NN_tanh_126_V(18'd4096),
    .my_NN_tanh_127_V(18'd4096),
    .my_NN_b_0_V(18'd3337),
    .my_NN_b_1_V(18'd3710),
    .my_NN_b_2_V(18'd520),
    .my_NN_b_3_V(18'd3741),
    .my_NN_b_4_V(18'd2590),
    .my_NN_b_5_V(18'd399),
    .my_NN_b_6_V(18'd1140),
    .my_NN_b_7_V(18'd2240),
    .my_NN_b_8_V(18'd3921),
    .my_NN_b_9_V(18'd3952),
    .my_NN_b_10_V(18'd645),
    .my_NN_b_11_V(18'd3975),
    .my_NN_w_0_V(18'd0),
    .my_NN_w_1_V(18'd0),
    .my_NN_w_2_V(18'd0),
    .my_NN_w_3_V(18'd0),
    .my_NN_w_4_V(18'd0),
    .my_NN_w_5_V(18'd0),
    .my_NN_w_6_V(18'd0),
    .my_NN_w_7_V(18'd0),
    .my_NN_w_8_V(18'd0),
    .my_NN_w_9_V(18'd0),
    .my_NN_w_10_V(18'd0),
    .my_NN_w_11_V(18'd0),
    .my_NN_w_12_V(18'd0),
    .my_NN_w_13_V(18'd0),
    .my_NN_w_14_V(18'd0),
    .my_NN_w_15_V(18'd0),
    .my_NN_w_16_V(18'd39205),
    .my_NN_w_17_V(18'd19880),
    .my_NN_w_18_V(18'd32779),
    .my_NN_w_19_V(18'd5811),
    .my_NN_w_20_V(18'd17275),
    .my_NN_w_21_V(18'd37508),
    .my_NN_w_22_V(18'd32448),
    .my_NN_w_23_V(18'd39300),
    .my_NN_w_24_V(18'd26859),
    .my_NN_w_25_V(18'd1462),
    .my_NN_w_26_V(18'd34780),
    .my_NN_w_27_V(18'd38256),
    .my_NN_w_28_V(18'd27800),
    .my_NN_w_29_V(18'd31037),
    .my_NN_w_30_V(18'd30438),
    .my_NN_w_31_V(18'd16065),
    .my_NN_w_32_V(18'd26848),
    .my_NN_w_33_V(18'd7011),
    .my_NN_w_34_V(18'd28919),
    .my_NN_w_35_V(18'd1303),
    .my_NN_w_36_V(18'd11342),
    .my_NN_w_37_V(18'd1891),
    .my_NN_w_38_V(18'd3978),
    .my_NN_w_39_V(18'd33728),
    .my_NN_w_40_V(18'd28460),
    .my_NN_w_41_V(18'd12988),
    .my_NN_w_42_V(18'd38921),
    .my_NN_w_43_V(18'd1410),
    .my_NN_w_44_V(18'd17970),
    .my_NN_w_45_V(18'd15628),
    .my_NN_w_46_V(18'd31355),
    .my_NN_w_47_V(18'd32571),
    .my_NN_w_48_V(18'd7654),
    .my_NN_w_49_V(18'd20060),
    .my_NN_w_50_V(18'd18251),
    .my_NN_w_51_V(18'd26472),
    .my_NN_w_52_V(18'd29055),
    .my_NN_w_53_V(18'd30911),
    .my_NN_w_54_V(18'd11305),
    .my_NN_w_55_V(18'd27840),
    .my_NN_w_56_V(18'd26832),
    .my_NN_w_57_V(18'd6660),
    .my_NN_w_58_V(18'd4874),
    .my_NN_w_59_V(18'd20412),
    .my_NN_w_60_V(18'd39311),
    .my_NN_w_61_V(18'd13942),
    .my_NN_w_62_V(18'd23972),
    .my_NN_w_63_V(18'd9167),
    .my_NN_n_V_i(my_NN_n_V),
    .my_NN_n_V_o(StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o),
    .my_NN_n_V_o_ap_vld(StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld)
);

my_NN_out_func StgValue_237_my_NN_out_func_fu_2870(
    .Y0(StgValue_237_my_NN_out_func_fu_2870_Y0),
    .Y0_ap_vld(StgValue_237_my_NN_out_func_fu_2870_Y0_ap_vld),
    .Y1(StgValue_237_my_NN_out_func_fu_2870_Y1),
    .Y1_ap_vld(StgValue_237_my_NN_out_func_fu_2870_Y1_ap_vld),
    .x0(x0),
    .x1(x1),
    .x2(x2),
    .x3(x3),
    .my_NN_c_0_V(18'd15385),
    .my_NN_c_1_V(18'd18245),
    .my_NN_c_2_V(18'd5224),
    .my_NN_c_3_V(18'd19646),
    .my_NN_c_4_V(18'd10362),
    .my_NN_c_5_V(18'd11206),
    .my_NN_c_6_V(18'd14317),
    .my_NN_c_7_V(18'd2839)
);

always @ (posedge CLK) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        my_NN_n_V <= 3'd0;
    end else if ((1'b1 == StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o_ap_vld)) begin
        my_NN_n_V <= StgValue_231_my_NN_NN_func_fu_2420_my_NN_n_V_o;
    end
end

always @ (posedge CLK) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x0 <= 18'd0;
    end else if ((1'b1 == StgValue_231_my_NN_NN_func_fu_2420_x0_o_ap_vld)) begin
        x0 <= StgValue_231_my_NN_NN_func_fu_2420_x0_o;
    end
end

always @ (posedge CLK) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x1 <= 18'd0;
    end else if ((1'b1 == StgValue_231_my_NN_NN_func_fu_2420_x1_o_ap_vld)) begin
        x1 <= StgValue_231_my_NN_NN_func_fu_2420_x1_o;
    end
end

always @ (posedge CLK) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x2 <= 18'd0;
    end else if ((1'b1 == StgValue_231_my_NN_NN_func_fu_2420_x2_o_ap_vld)) begin
        x2 <= StgValue_231_my_NN_NN_func_fu_2420_x2_o;
    end
end

always @ (posedge CLK) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x3 <= 18'd0;
    end else if ((1'b1 == StgValue_231_my_NN_NN_func_fu_2420_x3_o_ap_vld)) begin
        x3 <= StgValue_231_my_NN_NN_func_fu_2420_x3_o;
    end
end

assign Y0 = StgValue_237_my_NN_out_func_fu_2870_Y0;

assign Y1 = StgValue_237_my_NN_out_func_fu_2870_Y1;

assign ap_CS_fsm = 4'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign my_NN_ssdm_thread_load_fu_3320_p1 = 1'd0;

endmodule //my_NN
