// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module my_NN_out_func (
        Y0,
        Y0_ap_vld,
        Y1,
        Y1_ap_vld,
        x0,
        x1,
        x2,
        x3,
        my_NN_c_0_V,
        my_NN_c_1_V,
        my_NN_c_2_V,
        my_NN_c_3_V,
        my_NN_c_4_V,
        my_NN_c_5_V,
        my_NN_c_6_V,
        my_NN_c_7_V
);


output  [17:0] Y0;
output   Y0_ap_vld;
output  [17:0] Y1;
output   Y1_ap_vld;
input  [17:0] x0;
input  [17:0] x1;
input  [17:0] x2;
input  [17:0] x3;
input  [17:0] my_NN_c_0_V;
input  [17:0] my_NN_c_1_V;
input  [17:0] my_NN_c_2_V;
input  [17:0] my_NN_c_3_V;
input  [17:0] my_NN_c_4_V;
input  [17:0] my_NN_c_5_V;
input  [17:0] my_NN_c_6_V;
input  [17:0] my_NN_c_7_V;

wire  signed [29:0] grp_fu_688_p3;
wire  signed [29:0] grp_fu_719_p3;
wire  signed [29:0] p_Val2_1_fu_673_p2;
wire  signed [29:0] grp_fu_666_p3;
wire  signed [29:0] grp_fu_680_p3;
wire  signed [29:0] p_Val2_8_fu_704_p2;
wire  signed [29:0] grp_fu_697_p3;
wire  signed [29:0] grp_fu_711_p3;

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U263(
    .din0(x0),
    .din1(my_NN_c_0_V),
    .din2(p_Val2_1_fu_673_p2),
    .dout(grp_fu_666_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U264(
    .din0(x1),
    .din1(my_NN_c_2_V),
    .dout(p_Val2_1_fu_673_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U265(
    .din0(x2),
    .din1(my_NN_c_4_V),
    .din2(grp_fu_666_p3),
    .dout(grp_fu_680_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U266(
    .din0(x3),
    .din1(my_NN_c_6_V),
    .din2(grp_fu_680_p3),
    .dout(grp_fu_688_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U267(
    .din0(x0),
    .din1(my_NN_c_1_V),
    .din2(p_Val2_8_fu_704_p2),
    .dout(grp_fu_697_p3)
);

my_NN_mul_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 30 ))
my_NN_mul_mul_18sg8j_U268(
    .din0(x1),
    .din1(my_NN_c_3_V),
    .dout(p_Val2_8_fu_704_p2)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U269(
    .din0(x2),
    .din1(my_NN_c_5_V),
    .din2(grp_fu_697_p3),
    .dout(grp_fu_711_p3)
);

my_NN_mac_muladd_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
my_NN_mac_muladd_fYi_U270(
    .din0(x3),
    .din1(my_NN_c_7_V),
    .din2(grp_fu_711_p3),
    .dout(grp_fu_719_p3)
);

assign Y0_ap_vld = 1'b1;

assign Y1_ap_vld = 1'b1;

assign Y0 = {{grp_fu_688_p3[29:12]}};

assign Y1 = {{grp_fu_719_p3[29:12]}};

endmodule //my_NN_out_func
